### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of undefined

### ISSUE THREAD

**Issue by kylozw** [shd101wyy/markdown-preview-enhanced#102]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.8
**System**: Mac OS X 10.11.6
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getAttribute' of undefined

```
At /Users/kylo/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:976

TypeError: Cannot read property 'getAttribute' of undefined
    at getStructure (/Users/kylo/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:976:23)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.generateEbook (/Users/kylo/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:992:11)
    at HTMLDivElement.<anonymous> (/Users/kylo/.atom/packages/markdown-preview-enhanced/lib/exporter-view.coffee:140:26)
    at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:15.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:49.5.0 markdown-preview-enhanced:open-in-browser (div.markdown-preview-enhanced.native-key-bindings)
     -3:20.7.0 tree-view:reveal-active-file (atom-text-editor.editor.is-focused)
     -3:08.9.0 markdown-preview-enhanced:export-to-disk (div.line)
     -1:30 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -1:30 editor:newline (atom-text-editor.editor.is-focused)
     -1:29.9.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -1:29.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:29.6.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -1:23.2.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:10.6.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:09.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:02.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:53 markdown-preview-enhanced:export-to-disk (p.line)
     -0:18.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:09.9.0 markdown-preview-enhanced:export-to-disk (div.markdown-preview-enhanced.native-key-bindings)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-pdf",
      "markdown-toc"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "markdown-preview-enhanced": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.4 (active)
atomic-chrome, v0.3.0 (active)
emmet, v2.4.3 (active)
language-plantuml, v0.2.0 (active)
language-velocity, v0.1.2 (active)
linter, v1.11.16 (active)
linter-javac, v1.9.4 (active)
markdown-pdf, v1.5.0 (inactive)
markdown-preview-enhanced, v0.8.0 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.5.1 (active)
minimap, v4.24.7 (active)
plantuml, v0.1.2 (inactive)
plantuml-viewer, v0.7.0 (active)
script, v3.8.3 (inactive)
seti-syntax, v1.0.1 (active)
seti-ui, v1.3.2 (active)
tidy-markdown, v3.0.1 (active)
tool-bar, v1.0.1 (active)
tool-bar-markdown-writer, v0.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
Hi @kylozw , thanks for your reply.

Can I see your ebook entry file?

Thanks

**Comment by kylozw** [comment]
Sry I found there is an [EBook generation (beta)](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/ebook.md) to see first
So, I'll try it first

**Comment by shd101wyy** [comment]
没关系，如果你有什么问题或者需要我改的东西请告诉我。

**Comment by kylozw** [comment]
导出 epub 报错：
```
'ebook-convert' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```
终端能运行 ebook-convert 命令

**Comment by shd101wyy** [comment]
那你就重启下试试？  
还不行的话就重新安装下这个 package。

**Comment by kylozw** [comment]
重启和重装都无法解决。。

**Comment by shd101wyy** [comment]
升级到 `0.8.2` 试试？如果还不行的话，能否截张图（包括终端上运行的 `ebook-convert`）。
谢谢

**Comment by kylozw** [comment]
重装升级到 0.8.2 了
![image](https://cloud.githubusercontent.com/assets/5001813/17842246/568338ea-6853-11e6-9c16-4f83d02e9cc2.png)
![image](https://cloud.githubusercontent.com/assets/5001813/17842251/6a372806-6853-11e6-97fd-b8e7fefbd038.png)

**Comment by shd101wyy** [comment]
哦我貌似懂了问题在哪里了。  貌似是 `path` 的问题。
你试试从 `terminal` 中打开 `atom`? 例如 `atom 项目目录`  
如果还不行是是编辑 `init.coffee` 通过 `Application: Open Your Init Script` 然后添加以下代码后重启 atom.  
```coffee
process.env.PATH = ["/usr/local/bin", process.env.PATH].join(":")
```
貌似这里有个相似的 issue https://github.com/steelbrain/linter/issues/150

**Comment by kylozw** [comment]
找到原因了
因为原来我把 `calibre.app` 放在 `/Applications` 目录，命令行运行会报错：
```
➜  bin git:(master) ebook-convert
zsh: no such file or directory: /Users/kylo/Applications/calibre.app/Contents/MacOS/ebook-convert
```
所以我移动到了 `/Users/kylo/Applications` 目录，命令行能找到了，但是你这个就调用不到了；所以现在我放在 `/Applications` 下就可以了，命令行报错但是你的调用能成功
很奇怪的是明明是链接到 `/Applications/calibre.app/Contents/MacOS/ebook-convert`，但是却报上面的错：
```
lrwxr-xr-x  1 root  admin    54B  8 20 13:18 ebook-convert -> /Applications/calibre.app/Contents/MacOS/ebook-convert
```
