### ISSUE TITLE
Uncaught TypeError: scopeForLanguageName is not a function

### ISSUE THREAD

**Issue by btexpress** [shd101wyy/markdown-preview-enhanced#108]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Ubuntu 16.04.1
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.8.1
### Stack Trace

Uncaught TypeError: scopeForLanguageName is not a function

```
At /home/wtooles/.atom/packages/markdown-preview-enhanced/lib/md.coffee:503

TypeError: scopeForLanguageName is not a function
    at renderCodeBlock (/home/wtooles/.atom/packages/markdown-preview-enhanced/lib/md.coffee:503:24)
    at Object.<anonymous> (/home/wtooles/.atom/packages/markdown-preview-enhanced/lib/md.coffee:543:7)
    at exports.each (/opt/atom/resources/app.asar/node_modules/cheerio/lib/api/traversing.js:267:24)
    at resolveImagePathAndCodeBlock (/home/wtooles/.atom/packages/markdown-preview-enhanced/lib/md.coffee:509:12)
    at MarkdownPreviewEnhancedView.parseMD (/home/wtooles/.atom/packages/markdown-preview-enhanced/lib/md.coffee:770:10)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.renderMarkdown (/home/wtooles/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:353:29)
    at /home/wtooles/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:279:10
    at Config.module.exports.Config.observeKeyPath (/opt/atom/resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/opt/atom/resources/app.asar/src/config.js:141:21)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.initSettingsEvents (/home/wtooles/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:277:34)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.initEvents (/home/wtooles/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:148:6)
    at /home/wtooles/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:121:10
```
### Commands

```
     -0:45.7.0 settings-view:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/home/wtooles/git-repos",
    "themes": [
      "one-dark-ui",
      "Wild-Cherry"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
ask-stack, v2.2.0 (inactive)
atom-beautify, v0.29.10 (inactive)
atom-material-ui, v1.3.3 (inactive)
atom-terminal, v0.8.0 (inactive)
batman-light, v0.0.1 (inactive)
batman-syntax, v1.0.1 (inactive)
emmet, v2.4.3 (active)
file-icons, v1.7.18 (active)
firepad, v0.8.0 (inactive)
git-plus, v5.16.2 (inactive)
iceberg-syntax, v0.2.0 (inactive)
language-puppet, v0.21.0 (active)
linter, v1.11.16 (active)
linter-puppet, v1.0.0 (active)
linter-puppet-lint, v0.7.0 (active)
linter-puppet-parser, v0.1.1 (active)
markdown-preview-enhanced, v0.8.1 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-toc, v0.4.1 (inactive)
markdown-toolbar, v0.1.2 (active)
markdown-writer, v2.5.1 (inactive)
minimap, v4.24.7 (active)
pane-move-plus, v0.3.1 (inactive)
project-manager, v2.9.7 (active)
set-syntax, v0.3.0 (active)
sync-settings, v0.7.2 (active)
terminal-plus, v0.14.5 (active)
Wild-Cherry, v0.7.13 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
Hi @btexpress , thanks for your reply.

Does this error still happen after you restart atom? If so, please paste code snippet here.

Thanks

**Comment by shd101wyy** [comment]
I will close this old issue now, please reopen it if this problem still happens.
Thanks
