### ISSUE TITLE
Uncaught Error: Cannot find module '@shd101wyy/mume'

### ISSUE THREAD

**Issue by isuwei** [shd101wyy/markdown-preview-enhanced#1117]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0-beta0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.15.10

### Stack Trace

Uncaught Error: Cannot find module '@shd101wyy/mume'

```
At module.js:545

Error: Cannot find module '@shd101wyy/mume'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.37.0-beta0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:146072)
    at /packages/markdown-preview-enhanced/out/src/extension.js:11:14)
    at /packages/markdown-preview-enhanced/out/src/extension.js:566:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:1:688364)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:3545252)
    at Package.activateConfig (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:3534611)
    at PackageManager.t.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:894636)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:14:3069637)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:14:3059917)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:14:3059740)
    at new PackageCard (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:14:3051337)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:14:739588)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:14:740155)
    at new PackageDetailView (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:14:736726)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:916438)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:917159)
    at SettingsView.showDeferredPanel (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:917083)
    at SettingsView.initializePanels (~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:914540)
    at ~/AppData/Local/atom/app-1.37.0-beta0/resources/app/static/<embedded>:11:911716
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -0:25.2.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
markdown-preview-enhanced 0.15.10 
markdown-table-editor 1.1.1 
markdown-themeable-pdf 1.2.1 
seti-icons 1.5.4 
simplified-chinese-menu 5.3.5 
```

**Comment by shd101wyy** [comment]
Try remove `~/.mume` directory, then start atom?

**Comment by isuwei** [comment]
> 尝试删除`~/.mume`目录，然后启动原子？

OK~
