### ISSUE TITLE
Uncaught Error: Cannot find module 'twemoji'

### ISSUE THREAD

**Issue by janebuoy** [shd101wyy/markdown-preview-enhanced#1163]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: linux 5.1.14-121.current
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.16.2

### Stack Trace

Uncaught Error: Cannot find module 'twemoji'

```
At module.js:545

Error: Cannot find module 'twemoji'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/render-enhancers/emoji-to-svg.js:4:17)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/render-enhancers/emoji-to-svg.js:23:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/markdown-engine.js:37:24)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/markdown-engine.js:2088:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:22:25)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:101:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146462)
    at /packages/markdown-preview-enhanced/out/src/extension.js:11:14)
    at /packages/markdown-preview-enhanced/out/src/extension.js:561:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150720)
```

### Commands

```
     -2:38.1.0 settings-view:open (input.hidden-input)
  9x -2:08.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-notes 1.20.0 
autocomplete-bibtex 1.2.1 
dark-mode 4.0.2 
date 2.6.0 
emoji-syntax 1.7.6 
file-icons 2.1.33 
language-markdown 0.37.0 
markdown-helper 0.3.0 
markdown-preview-enhanced 0.16.2 
pigments 0.40.2 
replace-line-break 1.0.0 
tool-bar 1.1.11 
tool-bar-markdown 0.6.0 
wordcount 3.1.0 
```

**Comment by 3str** [comment]
Got the same error on MacOS Mojave.

**Comment by shd101wyy** [comment]
That's weird. I would assume atom failed to install the `twemoji` package. Could you try `cmd-shift-p` then run `Update Package Dependencies: Update` command? Thank you.

**Comment by janebuoy** [comment]
Unfortunately, that doesn't do it for me. It gives me "Package dependencies updated", neither before nor after restarting atom. Upon opening the first .md file after start I get "Failed to activate the markdown-preview-enhanced package" again.

**Comment by petermall** [comment]
I have the same problem:
Atom 1.38.2
markdown-preview-enhanced 0.16.2 
macOS 10.16.3

Update dependencies did not help. Issue came with the latest update...

Thank you for the great tool!

**Comment by shd101wyy** [comment]
I will go check the issue tonight. 
I don't have a mac with me right now, so I will go check after I get back home. 
Thank you.

**Comment by petermall** [comment]
Problem resolved for me... 
I very much deleted the plugin folder (~/.atom/packages/markdown-preview-enhanced), downloaded version 0.15.10 and copied it into this folder. Then I had the error, that the folder node_modules was missing... so I let Atom update to actual version (thinking to then overwrite it with 0.15.10). 
BUT: Error gone and 0.16.2 working. 

This is probably no help in finding the issue, but anyway I wanted to share it...

**Comment by shd101wyy** [comment]
Hi all,

I sincerely apologize that I am not able to fix it tonight (July 3, 2019).  
I got back home from work at around 9pm, and I was feeling exhausted.  
I promise to fix the issue by the end of this week, along with a few other bug fixes.

Thank you ;)

**Comment by shd101wyy** [comment]
I just published a new release. Please help check if it works for you guys. Thank you.

**Comment by janebuoy** [comment]
Yes, it is working again for me.

My former preview theme is gone, but that's probably a mistake on my part.

Thanks a lot for fixing the issue! Also, don't be too sorry for taking your time. It's a very nice tool and i guess most people really appreciate your efforts!

**Comment by 3str** [comment]
I reinstalled and it work again :-)
