### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Camypaper** [shd101wyy/markdown-preview-enhanced#118]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Unknown Windows Version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.8.3

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:184:7)
    at ImageHelperView.pasteImageFile (file:///C:/Users/goat/.atom/packages/markdown-preview-enhanced/lib/image-helper-view.coffee:122:45)
    at HTMLInputElement.<anonymous> (file:///C:/Users/goat/.atom/packages/markdown-preview-enhanced/lib/image-helper-view.coffee:90:12)
    at HTMLInputElement.jQuery.event.dispatch (C:\Users\goat\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (C:\Users\goat\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -1:42.9.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:42.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:40.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:39.6.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -1:34.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:30.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:26.1.0 markdown-preview-enhanced:image-helper (atom-text-editor.editor)
     -0:41.1.0 core:cancel (a.btn-issue.btn.btn-error)
     -0:38.9.0 markdown-preview-enhanced:image-helper (atom-text-editor.editor.is-focused)
     -0:17.3.0 core:cancel (a.)
     -0:15.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:14.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:14.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:12.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:12.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:09.8.0 markdown-preview-enhanced:image-helper (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "packagesWithKeymapsDisabled": []
  },
  "markdown-preview-enhanced": {
    "enableWikiLinkSyntax": false,
    "exportPDFPageFormat": "A4",
    "openPreviewPaneAutomatically": false
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-yeoman, v0.3.15 (active)
autocomplete-go, v1.1.1 (active)
builder-go, v1.0.1 (active)
git-plus, v5.16.2 (inactive)
go-config, v1.2.3 (active)
go-debug, v0.1.22 (active)
go-get, v1.0.4 (active)
go-plus, v4.2.0 (active)
godoc, v0.3.1 (active)
gofmt, v1.1.8 (active)
gometalinter-linter, v1.1.1 (active)
gorename, v1.0.3 (active)
json-schema, v0.1.15 (active)
linter, v1.11.16 (active)
linter-gcc, v0.6.15 (active)
markdown-preview-enhanced, v0.8.3 (active)
minimap, v4.24.7 (active)
navigator-godef, v1.0.4 (active)
omnisharp-atom, vundefined (active)
pdf-view, v0.50.0 (active)
tester-go, v1.0.6 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
Oh I see, you might need to follow `File -> Add Project Folder` to open a folder first.

**Comment by shd101wyy** [comment]
I added error message for this case.
closing this issue out.
thanks ;)
