### ISSUE TITLE
Uncaught Error: The WebView must be attached to the DOM and the dom-ready event emitted before th...

### ISSUE THREAD

**Issue by danbugs** [shd101wyy/markdown-preview-enhanced#1238]
**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.5
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.17.0

### Stack Trace

Uncaught Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:241

Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at getGuestInstanceId (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:241:13)
    at HTMLElement.send (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:272:77)
    at MarkdownPreviewEnhancedView.postMessage (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:542:26)
    at MarkdownPreviewEnhancedView.syncPreview (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:402:25)
    at disposables.add.editorElement.onDidChangeScrollTop (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:361:18)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1213350)
    at TextEditorComponent.setScrollTop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:115819)
    at TextEditorComponent.didScrollDummyScrollbar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:93436)
```

### Non-Core Packages

```
language-gfm-enhanced 0.92.0 
markdown-preview-enhanced 0.17.0 
```

**Comment by tandriamil** [comment]
Also happened to me on the following system :
**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**Node**: v10.11.0
**OS**: Mac OS 10.15.2
**markdown-preview-enhanced**: 0.17.3

The error was thrown when I was dragging the tab to move it to another place in the same window (e.g; it was the 10th tab, I moved it to the 5th position).
