### ISSUE TITLE
eBook > PDF results in a PDF file with only "nullnull" in it

### ISSUE THREAD

**Issue by miskovics** [shd101wyy/markdown-preview-enhanced#1287]
Up-to-date Markdown Preview Enhanced and Calibre on Ubuntu 18.04.

1. Download and extract https://github.com/shd101wyy/ebook-example
2. Open ˋALICE.mdˋ
3. Open Preview pane if it does not open automatically
4. Fix path to cover image (ˋ\cover.jpgˋ --> ˋcover.jpgˋ) in ˋALICE.mdˋ
4. Click ˋePubˋ > ˋPDFˋ on Preview pane

ALICE.pdf is generated, but instead of the 3 chapters, it contains only the cover image and "nullnull". Same behavior with other ˋ.mdˋ files.

**Comment by shd101wyy** [comment]
Yeah I see. I will take a look. Thanks.

**Comment by shd101wyy** [comment]
Should be fixed now. Thanks.

**Comment by miskovics** [comment]
I've updated to the newest version 0.17.5 and now I get an exception

```
Error: Command failed: ebook-convert /tmp/mume202011-6956-ydaqil.55ic.html /home/g/Desktop/ebook-example-master/ALICE.pdf --level1-toc //[@ebook-toc-level-1]/@heading --level2-toc //[@ebook-toc-level-2]/@heading --level3-toc //*[@ebook-toc-level-3]/@heading --no-chapters-in-toc --title Alice's Adventures in Wonderland --cover /home/g/Desktop/ebook-example-master/cover.jpg --margin-top=72 --margin-bottom=72 --margin-left=72 --margin-right=72 --paper-size letter --pdf-default-font-size=14 --pdf-header-template SECTION --pdf-footer-template

PAGENUM
Traceback (most recent call last): File "site.py", line 77, in main File "site-packages/calibre/ebooks/conversion/cli.py", line 401, in main File "site-packages/calibre/ebooks/conversion/plumber.py", line 1275, in run File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 188, in convert File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 255, in convert_text File "site-packages/calibre/ebooks/pdf/html_writer.py", line 1221, in convert File "site-packages/calibre/ebooks/pdf/html_writer.py", line 606, in add_toc File "site-packages/calibre/ebooks/pdf/html_writer.py", line 585, in create ValueError: Invalid page number: 3
```

The logged command above is not complete, the shell wants more in a terminal.

```
~/Desktop/ebook-example-master$ ebook-convert /tmp/mume202011-6225-1c4d7zc.ep8yf.html /home/g/Desktop/ebook-example-master/ALICE.pdf --level1-toc //[@ebook-toc-level-1]/@heading --level2-toc //[@ebook-toc-level-2]/@heading --level3-toc //*[@ebook-toc-level-3]/@heading --no-chapters-in-toc --title Alice's Adventures in Wonderland --cover /home/g/Desktop/ebook-example-master/cover.jpg --margin-top=72 --margin-bottom=72 --margin-left=72 --margin-right=72 --paper-size letter --pdf-default-font-size=14 --pdf-header-template SECTION --pdf-footer-template
> ^C
~/Desktop/ebook-example-master$ 
```

I also had to fix ALICE.md. This time not only "/cover.jpg", but also the path to the embedded .md's.

Does the PDF conversion work at your place?
