### ISSUE TITLE
Uncaught Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by marshallgunnell** [shd101wyy/markdown-preview-enhanced#1293]
I recently updated to v0.17.5 and received the following error:

> Uncaught Error: Cannot find module `tslib`

Uninstalled and reinstalled--same issue.

> Uncaught Error: Cannot find module `tslib`

internal/modules/cjs/loader.js:604

```
Error: Cannot find module 'tslib'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (file:///private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app.asar/static/index.js:61:43)
    at require (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/JP26143/.atom/packages/markdown-preview-enhanced/node_modules/less/dist/less.cjs.js:3:13)
    at Object.<anonymous> (/Users/JP26143/.atom/packages/markdown-preview-enhanced/node_modules/less/dist/less.cjs.js:10871:3)
    at Module.get_Module._compile (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/JP26143/.atom/packages/markdown-preview-enhanced/node_modules/less/index.js:1:173)
    at Object.<anonymous> (/Users/JP26143/.atom/packages/markdown-preview-enhanced/node_modules/less/index.js:3:3)
    at Module.get_Module._compile (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (file:///private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/JP26143/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/utility.js:14:14)
    at Object.<anonymous> (/Users/JP26143/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/utility.js:604:3)
    at Module.get_Module._compile (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
```

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.17.5

### Stack Trace

Uncaught Error: Cannot find module 'tslib'

```
At internal/modules/cjs/loader.js:604

Error: Cannot find module 'tslib'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/markdown-preview-enhanced/node_modules/less/dist/less.cjs.js:3:13)
    at /packages/markdown-preview-enhanced/node_modules/less/dist/less.cjs.js:10871:3)
    at Module.get_Module._compile (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/markdown-preview-enhanced/node_modules/less/index.js:1:173)
    at /packages/markdown-preview-enhanced/node_modules/less/index.js:3:3)
    at Module.get_Module._compile (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/utility.js:14:14)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/utility.js:604:3)
    at Module.get_Module._compile (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/private/var/folders/x9/30wrf2qs6bv6vxrj17h1y0b40000gp/T/AppTranslocation/BF7722C8-E933-42A5-BE2A-272F1203CB2C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.17 
atom-image-resize 0.3.0 
atomic-vale 1.9.0 
busy-signal 2.0.1 
git-log 0.4.1 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.1 
markdown-preview-enhanced 0.17.5 
```

**Comment by hhysj** [comment]
+1

**Comment by shd101wyy** [comment]
try again? thanks

**Comment by shd101wyy** [comment]
Seems to be fixed in `0.17.7`. Thanks ;)

**Comment by marshallgunnell** [comment]
Sweet, it's working now. Thanks a lot.

**Comment by sbmueller** [comment]
I experience the same error with the current master:
```
internal/modules/cjs/loader.js:968
  throw err;
  ^
Error: Cannot find module 'tslib'
Require stack:
- /home/me/.local/share/nvim/plugged/markdown-preview.nvim/app/lib/app/index.js
- /home/me/.local/share/nvim/plugged/markdown-preview.nvim/app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/me/.local/share/nvim/plugged/markdown-preview.nvim/app/lib/app/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/me/.local/share/nvim/plugged/markdown-preview.nvim/app/lib/app/index.js',
    '/home/me/.local/share/nvim/plugged/markdown-preview.nvim/app/index.js'
  ]
}

```

**Comment by MarkoSagadin** [comment]
I have the same issue, but this is not correct repo @sbmueller :D 

This comment helped me to set it up correctly: https://github.com/iamcco/markdown-preview.nvim/issues/188#issuecomment-841356921

I had to ensure that yarn is installed and that tslib is added. I did not need to reinstall npm, and I have quite old version as I see now, `npm --version` returns `6.14.4`

**Comment by sbmueller** [comment]
Oops sorry, damn GitHub repo suggestions :smile:
