### ISSUE TITLE
Failed to activate the markdown-preview-enhanced package

### ISSUE THREAD

**Issue by marcovidero** [shd101wyy/markdown-preview-enhanced#1297]
Update from previous version broke package.

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: "Fedora release
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.17.6

### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At Cannot find module 'tslib'

Error: Cannot find module 'tslib'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/markdown-preview-enhanced/node_modules/less/dist/less.cjs.js:3:13)
    at /packages/markdown-preview-enhanced/node_modules/less/dist/less.cjs.js:10871:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/markdown-preview-enhanced/node_modules/less/index.js:1:173)
    at /packages/markdown-preview-enhanced/node_modules/less/index.js:3:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/utility.js:14:14)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/utility.js:604:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
file-icons 2.1.39 
markdown-preview-enhanced 0.17.6 
```

**Comment by jakobzhao** [comment]
I met the same issue. Hope it could be solved soon.

**Comment by jnstllng** [comment]
Same issue here, downgrading to v0.17.5 did not help.

**Comment by mintjelly7** [comment]
me too

**Comment by olivier-singla** [comment]
Me too

**Comment by parkin** [comment]
I have the same issue.

The package works when I install via apm and git.

`apm install git@github.com:shd101wyy/markdown-preview-enhanced.git`

Note at the time I tried this the master commit matched the v0.17.6 commit: a1ba81a

**Comment by shd101wyy** [comment]
Hmm sorry I actually don’t know where the tslib issue is from. 

Can anyone please help? I am not able to run “apm install markdown-preview-enhanced” successfully because I am blocked by the “Great Firewall” now unfortunately. 

I cleaned up the yarn.lock file yesterday but apparently it didn’t help

**Comment by shd101wyy** [comment]
btw downgrading to 0.17.4 should work

**Comment by shd101wyy** [comment]
Let me try to upgrade the `typescript` dependency.

**Comment by shd101wyy** [comment]
`0.17.7` is released. Can someone try it to see if the issue is fixed? Thanks

**Comment by jnstllng** [comment]
Seems to work for me, just updated and the package activates as usual.

**Comment by mintjelly7** [comment]
> `0.17.7` is released. Can someone try it to see if the issue is fixed? Thanks

Work well👍

**Comment by parkin** [comment]
0.17.7 works for me too, thanks!

**Comment by olivier-singla** [comment]
Works great now, thanks!

**Comment by junwei-wang** [comment]
0.17.7 solved
