### ISSUE TITLE
Failed to activate the markdown-preview-enhanced package

### ISSUE THREAD

**Issue by WangHongweiBJTU** [shd101wyy/markdown-preview-enhanced#1312]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.17.7

### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At Cannot find module '@shd101wyy/mume'

Error: Cannot find module '@shd101wyy/mume'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/markdown-preview-enhanced-master/out/src/extension.js:12:14)
    at /packages/markdown-preview-enhanced-master/out/src/extension.js:567:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:1:727373)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3325206)
    at Package.activateNow (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3313190)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1213350)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:382998)
    at activatePromise.Promise.all.then (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:381749)
```

### Commands

```
```

### Non-Core Packages

```
language-latex 1.2.0 
latex 0.50.2 
markdown-preview-enhanced 0.17.7 
pdf-view 0.71.0 
```

**Comment by chrisroberts7577** [comment]
Same..Mojave OS

**Comment by santiregui** [comment]
Solved it by upgrading atom to V 1.52.0 (Ubuntu 18)
