### ISSUE TITLE
Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by Terminl3nt** [shd101wyy/markdown-preview-enhanced#135]
`
Cannot read property 'error' of undefined
Cannot read property 'error' of undefined
Hide Stack Trace
TypeError: Cannot read property 'error' of undefined
    at file:///C:/Users/Administrator/.atom/packages/atom-beautify/src/beautifiers/remark.coffee:42:10
    at Promise._execute (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\debuggability.js:299:9)
    at Promise._resolveFromExecutor (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:77:14)
    at Remark.module.exports.Remark.beautify (file:///C:/Users/Administrator/.atom/packages/atom-beautify/src/beautifiers/remark.coffee:36:16)
    at file:///C:/Users/Administrator/.atom/packages/atom-beautify/src/beautifiers/index.coffee:316:24
    at Promise._execute (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\debuggability.js:299:9)
    at Promise._resolveFromExecutor (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:77:14)
    at file:///C:/Users/Administrator/.atom/packages/atom-beautify/src/beautifiers/index.coffee:238:18
    at tryCatcher (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:636:18)
    at PromiseArray._resolve (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:572:26)
    at Promise._settlePromise0 (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:431:57)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:431:57)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:431:57)
    at ReductionPromiseArray._resolve (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\reduce.js:61:19)
    at Promise.completed [as _fulfillmentHandler0] (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\reduce.js:122:15)
    at Promise._settlePromise (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:564:21)
    at Promise._settlePromise0 (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:148:10)
    at Async.drainQueues (C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
CLOSE ALL
Cannot read property 'error' of undefined
Cannot read property 'error' of undefined
Show Stack Trace
`

**Comment by shd101wyy** [comment]
Hi @Terminl3nt ,

It seems to be a bug of **atom-beautify** but not **markdown-preview-enhanced**.

Thanks
