### ISSUE TITLE
Installing "markdown-preview-enhanced@0.18.2" failed

### ISSUE THREAD

**Issue by jinmang2** [shd101wyy/markdown-preview-enhanced#1395]
Hi!
I'm facing an error, and plz give me a solution...

The error is as follows;
```
Installing “markdown-preview-enhanced@0.18.2” failed.Hide output…
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\jinma\.atom\packages\markdown-preview-enhanced\node_modules\@shd101wyy\mume\styles\prism_theme\atom-dark.css'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:696:12)
    at WriteStream.emit (events.js:182:13)
    at C:\Users\jinma\AppData\Local\atom\app-1.47.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:211:14
    at C:\Users\jinma\AppData\Local\atom\app-1.47.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:169:20)
```

what's wrong on version 0.18.2 or my windows10?
i want to help!

**Comment by shd101wyy** [comment]
Try reinstalling it first.

**Comment by saitros** [comment]
@shd101wyy 
Hi! I have same problem to use it. 
Unfortunately, your commit didn't work at my win 10 
> Try reinstalling it first.

i want to help too :D

**Comment by shd101wyy** [comment]
Which version of atom are you guys using?
