### ISSUE TITLE
Just found this problem.

### ISSUE THREAD

**Issue by AJohn11** [shd101wyy/markdown-preview-enhanced#1402]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.17.7

### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At Cannot find module '@shd101wyy/mume'
Require stack:
- C:\Users\JohnsonGao\.atom\packages\markdown-preview-enhanced-0.17.7\out\src\extension.js
- C:\Users\JohnsonGao\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html

Error: Cannot find module '@shd101wyy/mume'
Require stack:
- C:\Users\JohnsonGao\.atom\packages\markdown-preview-enhanced-0.17.7\out\src\extension.js
- C:\Users\JohnsonGao\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /packages/markdown-preview-enhanced/out/src/extension.js:12:14)
    at /packages/markdown-preview-enhanced/out/src/extension.js:567:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3310163)
    at Package.activateNow (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3298147)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1201250)
    at Emitter.emit (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1202691)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:383182)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:381933
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-python-run 0.9.7 
busy-signal 2.0.1 
date 2.6.0 
highlight-selected 0.17.0 
intentions 1.1.5 
language-latex 1.2.0 
language-markdown 0.37.0 
latex 0.50.2 
linter 2.3.1 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.8.1 
markdown-image-paste 2.5.2 
markdown-image-paste-delete 0.3.0 
markdown-img-paste 0.4.0 
markdown-preview-enhanced 0.17.7 
markdown-preview-enhanced 0.17.7 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.2 
markdown-themeable-pdf 1.2.1 
minimap 4.29.9 
open-recent 5.0.0 
pdf-view 0.72.0 
```

**Comment by gabyx** [comment]
mume is the engine this extension is built on top. did you reinstall the extension? did it work?
