### ISSUE TITLE
Package fails to activate (unexpected token)

### ISSUE THREAD

**Issue by AdrienMatricon** [shd101wyy/markdown-preview-enhanced#1455]
[Enter steps to reproduce:]

1. Install the package
2. The message is immediately shown (and is shown again when opening Atom, even after a complete reboot)

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 18.04.5
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.18.5

### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At Unexpected token ...

SyntaxError: Unexpected token ...
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-preview-enhanced/node_modules/mkdirp/index.js:1:172)
    at /packages/markdown-preview-enhanced/node_modules/mkdirp/index.js:33:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:19:16)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:120:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-preview-enhanced/out/src/extension.js:14:14)
    at /packages/markdown-preview-enhanced/out/src/extension.js:590:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
```

### Commands

```
```

### Non-Core Packages

```
markdown-preview-enhanced 0.18.5 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by kachkaev** [comment]
The version of Atom you are using is from April 2018:
https://github.com/atom/atom/releases/tag/v1.26.1

Worth upgrading to the latest:
https://github.com/atom/atom/releases

This should resolve the error because the latest Atom will have a better JavaScript parser.

**Comment by AdrienMatricon** [comment]
I had installed/updated atom through apt, but indeed it seems that the version I got from the default apt repositories isn't recent.
I added atom's apt repository to get access to a more recent one and that did solve the issue. Thanks.
