### ISSUE TITLE
Uncaught Error: Cannot find module 'browser-window'Error: Cannot find module 'browser-window'  ...

### ISSUE THREAD

**Issue by f-r-i-t-z** [shd101wyy/markdown-preview-enhanced#150]
[Enter steps to reproduce below:]
1. trying to convert my to pdf..
2.  my error or something more here? ;-)

**Atom Version**: 1.10.2
**Electron Version**: 1.4.1
**System**: "Manjaro Linux"
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.8.7
### Stack Trace

Uncaught Error: Cannot find module 'browser-window'
Error: Cannot find module 'browser-window'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217

Error: Cannot find module 'browser-window'
Error: Cannot find module 'browser-window'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217:13)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.printPDF (/home/nash/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:955:39)
    at /home/nash/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1003:12
    at FSReqWrap.wrapper [as oncomplete] (fs.js:747:5)
```
### Commands

```
  2x -1:58 core:backspace (atom-text-editor.editor.is-focused)
     -1:53.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:43.9.0 markdown-preview-enhanced:export-to-disk (h3#nexus-6phttpforumxda-developerscomnexus-6p-huawei-nexus-6p-at-xda-developers.sync-line)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "language-gfm",
      "markdown-folder",
      "zotero-citations"
    ]
  },
  "markdown-preview-enhanced": {
    "enableTypographer": true,
    "exportPDFPageFormat": "A4",
    "scrollDuration": "80"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (active)
language-markdown, v0.16.3 (active)
markdown-folder, v0.5.0 (inactive)
markdown-preview-enhanced, v0.8.7 (active)
markdown-preview-plus, v2.4.0 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.6.1 (inactive)
tool-bar, v1.0.1 (active)
tool-bar-markdown-writer, v0.2.0 (active)
zotero-citations, v0.19.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
Can you restart your atom to see if the same issue still happens?
Thanks

**Comment by f-r-i-t-z** [comment]
still the error. 
Anything more that I can post here to help?

**Comment by f-r-i-t-z** [comment]
Trying to export to pandoc I receive "Output format need to be specified"..
I'm to do a complete wipe from eletron/atom and try again from start.

**Comment by shd101wyy** [comment]
For `pandoc document export`, please read [doc](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/docs/advanced-export.md)

as for the `browser-window` bug, I don't know why this happens. I will notice you once I find a solution.   

Thanks

**Comment by shd101wyy** [comment]
It seems that electron api changed. I will fix this issue in next release, thanks.
