### ISSUE TITLE
Can TypeScript snippets be run?

### ISSUE THREAD

**Issue by aanton** [shd101wyy/markdown-preview-enhanced#1523]
Hi!

I want to run TypeScript snippets but I get errors.

This is my code (i have changed backticks with hashtags to display the code properly):

```ts
###ts {cmd=tsc}
class Greeter {
  // property
  greeting: string;

  // constructor
  constructor(message: string) {
    this.greeting = message; // member access using 'this'
  }

  // method
  greet() {
    return 'Hello, ' + this.greeting;
  }
}

// Call the constructor using 'new' to create a new object with the Greeter shape and initialize it
let greeter = new Greeter('world');
console.log(greeter.greet());
###
```

And i get this error:

> error TS6231: Could not resolve the path '/home/.../474ehdgbn_code_chunk' with the extensions: '.ts', '.tsx', '.d.ts'.

The problem is that TypeScript require that the executed file has a properly extension. Changing from `tsc` to `ts-node` also fails, but the error is different:

> /home/.../vu42brqa0_code_chunk:3
>   greeting: string;
>   
> 
> SyntaxError: Unexpected identifier
>     at wrapSafe (internal/modules/cjs/loader.js:979:16)
>     at Module._compile (internal/modules/cjs/loader.js:1027:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at main (/usr/lib/node_modules/ts-node/src/bin.ts:198:14)
>     at Object. (/usr/lib/node_modules/ts-node/src/bin.ts:288:3)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

I have also tried using `cat` of the `$input_file` and pipe it to `ts-node`.

Thanks for any help!

**Comment by svallory** [comment]
I know it's been a long time, but yes you can!

First install typescript and ts-node globally with

```
npm i -g typescript ts-node
```

Then set `ts-node` as the `cmd` in your code block:

    ```typescript {cmd="ts-node" output="text"}
        let this_works = true;

        if (this_works) {
            console.log('YEY!! It works!');
        }
    ```

@shd101wyy you can close this one

**Comment by lokhmakov** [comment]
You can create typescript file in the same folder run with import it like this:

```md
\`\`\`typescript {cmd="ts-node" args=["your-file.ts"]}
\`\`\`

@import "your-file.ts"
```

In this case u can use `import` with tsconfig like this:

```json
{
  "compilerOptions": {
    "target": "ES2015", 
    "module": "commonjs", 
    "lib": ["es6"], 
    "declaration": true,
    "strict": true, 
    "noImplicitAny": true,   
    "moduleResolution": "node",   
    "esModuleInterop": true,  
    "forceConsistentCasingInFileNames": true
  }
}
```

**Comment by svallory** [comment]
### Update!!
`ts-node` does not work anymore since it will not treat a file without `.ts` extension as typescript and there's no option to force it to.

I'm using `deno` now!

````
```typescript {cmd="deno" args=["run", "-"] stdin}
````
```ts
class Message {
	constructor(
		public readonly name: string,
		public readonly data: Record<string, any>
	) {}
}

const msg: Message = new Message("Test", {
	test: "Deno should work",
	success: true,
});

console.info(msg.constructor.name, JSON.stringify(msg, null, 2));
```
````
```
````
#### Output:
```
Message {
  "name": "Test",
  "data": {
    "test": "Deno should work",
    "success": true
  }
}
```
