### ISSUE TITLE
Uncaught TypeError: this.webview.getWebContents is not a function

### ISSUE THREAD

**Issue by ZizhengYang** [shd101wyy/markdown-preview-enhanced#1557]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.18.10

### Stack Trace

Uncaught TypeError: this.webview.getWebContents is not a function

```
At C:\Users\username\.atom\packages\markdown-preview-enhanced\out\src\preview-content-provider.js:81

TypeError: this.webview.getWebContents is not a function
    at /packages/markdown-preview-enhanced/out/src/preview-content-provider.js:81:26)
    at WebViewImpl.dispatchEvent (electron/js2c/renderer_init.js:155:2221)
    at dispatchEvent (electron/js2c/renderer_init.js:143:1883)
    at electron/js2c/renderer_init.js:143:3008
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:127:872)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
```

### Non-Core Packages

```
counter 0.3.5 
file-type-icons 1.3.4 
language-markdown 0.37.0 
markdown-cell-highlight 1.2.0 
markdown-image-assistant 0.2.2 
markdown-image-paste-delete 0.3.0 
markdown-preview-enhanced 0.18.10 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.3 
```

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.18.10

### Stack Trace

Uncaught TypeError: this.webview.getWebContents is not a function

```
At C:\Users\username\.atom\packages\markdown-preview-enhanced\out\src\preview-content-provider.js:81

TypeError: this.webview.getWebContents is not a function
    at /packages/markdown-preview-enhanced/out/src/preview-content-provider.js:81:26)
    at WebViewImpl.dispatchEvent (electron/js2c/renderer_init.js:155:2221)
    at dispatchEvent (electron/js2c/renderer_init.js:143:1883)
    at electron/js2c/renderer_init.js:143:3008
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:127:872)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
```

### Non-Core Packages

```
counter 0.3.5 
file-type-icons 1.3.4 
language-markdown 0.37.0 
markdown-cell-highlight 1.2.0 
markdown-image-assistant 0.2.2 
markdown-image-paste-delete 0.3.0 
markdown-preview-enhanced 0.18.10 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.3 
```

**Comment by shd101wyy** [comment]
应该是修好了，更新下插件再试试

**Comment by GrazingScientist** [comment]
Now, I found a real use for Google Translate 🙈 . Thanks for the quick update, @shd101wyy
