### ISSUE TITLE
重试安装多次 启动atom 报错

### ISSUE THREAD

**Issue by jdmengxiangtao** [shd101wyy/markdown-preview-enhanced#1776]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: macOS 12.1
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.19.6

### Stack Trace

Uncaught SyntaxError: Unexpected token ...

```
At /Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:97

SyntaxError: Unexpected token ...
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-preview-enhanced/node_modules/mkdirp/index.js:1:172)
    at /packages/markdown-preview-enhanced/node_modules/mkdirp/index.js:33:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:18:16)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:117:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-preview-enhanced/out/src/extension.js:13:14)
    at /packages/markdown-preview-enhanced/out/src/extension.js:568:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
```

### Commands

```
```

### Non-Core Packages

```
markdown-image-assistant 0.2.2 
markdown-preview-enhanced 0.19.6 
```

**Comment by shd101wyy** [comment]
atom 版本的不维护了。因为 atom 编辑器都不被官方维护了。
推荐使用 vscode
