### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, open 'C:\Users\user.atom\compile-cache\coffee\9a255e28c8326fd363f58002e56addd7cc854459.js'

### ISSUE THREAD

**Issue by Vanni-Fan** [shd101wyy/markdown-preview-enhanced#190]
### File 9a255e28c8326fd363f58002e56addd7cc854459.js not exists.

Reinstall markdown-preview-enhanced , the problems still exist too.
----

**Atom Version**: 1.12.0-beta5
**Electron Version**: 1.3.6
**System**: Windows 7
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.8.9

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'C:\Users\user\.atom\compile-cache\coffee\9a255e28c8326fd363f58002e56addd7cc854459.js'

```
At fs.js:640

Error: EPERM: operation not permitted, open 'C:\Users\user\.atom\compile-cache\coffee\9a255e28c8326fd363f58002e56addd7cc854459.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.writeFileSync (C:\Users\user\AppData\Local\atom\app-1.12.0-beta5\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:281:17)
    at writeCachedJavascript (C:\Users\user\AppData\Local\atom\app-1.12.0-beta5\resources\app.asar\src\compile-cache.js:97:6)
    at compileFileAtPath (C:\Users\user\AppData\Local\atom\app-1.12.0-beta5\resources\app.asar\src\compile-cache.js:78:7)
    at Object.value [as .coffee] (C:\Users\user\AppData\Local\atom\app-1.12.0-beta5\resources\app.asar\src\compile-cache.js:200:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (C:\Users\user\AppData\Local\atom\app-1.12.0-beta5\resources\app.asar\src\native-compile-cache.js:50:27)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.initEvents (file:///C:/Users/user/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:144:58)
    at file:///C:/Users/user/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:126:16
```

### Commands

```
     -7:45.9.0 markdown-preview-enhanced:toggle (atom-text-editor.editor.is-focused)
     -5:24.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -5:21.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -5:12.1.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -5:10.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -5:10.1.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -5:09.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:07.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.mini.is-focused)
     -5:07.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:04.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
 17x -5:03.6.0 core:select-left (atom-text-editor.editor.mini.is-focused)
     -5:01.8.0 core:delete (atom-text-editor.editor.mini.is-focused)
     -5:01.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:46.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:45 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10 markdown-preview-enhanced:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "vim-mode"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
aligner, v0.22.2 (active)
atom-alignment, v0.12.1 (active)
atom-beautify, v0.29.13 (inactive)
atom-html-preview, v0.1.22 (active)
glowing-cursor, v0.1.1 (active)
highlight-line, v0.11.1 (active)
language-markdown, v0.18.1 (active)
markdown-folder, v0.5.0 (inactive)
markdown-format, v2.5.1 (active)
markdown-pdf, v1.5.0 (inactive)
markdown-preview-enhanced, v0.8.9 (active)
markdown-preview-plus, v2.4.0 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-themeable-pdf, v1.2.0 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.6.1 (inactive)
minimap, v4.25.6 (active)
pandoc, v0.2.2 (inactive)
php-class-tree, v1.0.0 (inactive)
script, v3.11.1 (inactive)
simplified-chinese-menu, v3.5.0 (active)
sync-settings, v0.7.2 (active)
tidy-markdown, v3.0.1 (active)
valign, v1.1.3 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.0 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.3 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.102.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
不打清楚啊，重启下试试？（一般来说安装完得重启）
