### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by AdamBear-Me** [shd101wyy/markdown-preview-enhanced#191]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.10.1
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.8.9

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:341

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/xiongchao/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:2:25)
    at Object.<anonymous> (/Users/xiongchao/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.MarkdownPreviewEnhanced.startMDPreview (/Users/xiongchao/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:102:35)
    at Object.module.exports.MarkdownPreviewEnhanced.toggle (/Users/xiongchao/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:99:8)
    at atom-workspace.subscriptions.add.atom.commands.add.markdown-preview-enhanced:toggle (/Users/xiongchao/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:31:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:26 application:open (atom-text-editor.editor.is-focused)
     -0:00.1.0 markdown-preview-enhanced:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
markdown-preview-enhanced, v0.8.9 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
Hi @AdamBear-Me , this shouldn't happen in theory. 
Could you please try restart atom? 
Or run command `Update Package Dependencies: Update` then restart:  
<img width="593" alt="screen shot 2016-11-10 at 11 28 30 am" src="https://cloud.githubusercontent.com/assets/1908863/20187181/e4d62cb4-a738-11e6-9f10-027217dc1252.png">

**Comment by AdamBear-Me** [comment]
I executed the command on your prompt and restart atom, but there's still the same mistake, as long as the order:control+shift+m, the error will occur.

**Comment by shd101wyy** [comment]
Delete this package, then install from the command line.  
```sh
apm install markdown-preview-enhanced
```

**Comment by shd101wyy** [comment]
I mean run the command in terminal.

**Comment by AdamBear-Me** [comment]
Reinstall markdown-preview-enhanced is OK, Thank you.
