### ISSUE TITLE
Uncaught Error: Cannot find module './CACHE'

### ISSUE THREAD

**Issue by dymaxionkim** [shd101wyy/markdown-preview-enhanced#234]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.9.0

### Stack Trace

Uncaught Error: Cannot find module './CACHE'

```
At module.js:457

Error: Cannot find module './CACHE'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/opt/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/dong/.atom/packages/markdown-preview-enhanced/lib/process-graphs.coffee:10:9)
    at Object.<anonymous> (/home/dong/.atom/packages/markdown-preview-enhanced/lib/process-graphs.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/dong/.atom/packages/markdown-preview-enhanced/lib/pandoc-wrapper.coffee:11:17)
    at Object.<anonymous> (/home/dong/.atom/packages/markdown-preview-enhanced/lib/pandoc-wrapper.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/dong/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:14:17)
    at Object.<anonymous> (/home/dong/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

### Commands

```
     -0:00.3.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ],
    "telemetryConsent": "limited"
  },
  "markdown-preview-enhanced": {
    "exportPDFPageFormat": "A4",
    "mathRenderingOption": "MathJax"
  }
}
```

### Installed Packages

```coffee
# User
atom-csv-markdown, v1.0.2 (inactive)
emmet, v2.4.3 (active)
ink, v0.6.2 (active)
julia-client, v0.5.11 (active)
language-julia, v0.10.0 (active)
latex-completions, v0.3.2 (active)
markdown-image-helper, v1.0.4 (active)
markdown-preview-enhanced, v0.9.0 (active)
script, v3.14.0 (inactive)
tool-bar, v1.0.1 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by SamaelChen** [comment]
I have the same error

**Comment by shd101wyy** [comment]
@dymaxionkim @SamaelChen , sorry my bad, should be fixed now...

**Comment by SamaelChen** [comment]
![selection_028](https://cloud.githubusercontent.com/assets/5146128/21924089/7498b870-d9b2-11e6-8de2-838a6f0b843f.png)
Does this issue matter? I didn't see it before I upgrade Atom. Well, I also upgrade this plugin. I'm not sure which one cause this error. @shd101wyy

**Comment by shd101wyy** [comment]
Don't worry about it, it's just a warning ⚠️ . I will fix it in the future 😂.

**Comment by shd101wyy** [comment]
@SamaelChen should be fixed now, thanks :)

**Comment by dymaxionkim** [comment]
Wow Thank you!
