### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dependencies' of undefined

### ISSUE THREAD

**Issue by soulawaker** [shd101wyy/markdown-preview-enhanced#237]
[Enter steps to reproduce below:]

I tried to 'export to disk'(for HTML) on preview tab. 
1. move cursor on markdown preview tab
2. call popup menu with mouse right click
3. chose 'export to disk' with checking CDN option then click export button.
4. This error produced.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: elementary OS
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.9.2

### Stack Trace

Uncaught TypeError: Cannot read property 'dependencies' of undefined

```
At /home/[user]/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1000

TypeError: Cannot read property 'dependencies' of undefined
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.getHTMLContent (/home/[user]/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1000:40)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.saveAsHTML (/home/[user]/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1125:20)
    at HTMLDivElement.<anonymous> (/home/[user]/.atom/packages/markdown-preview-enhanced/lib/exporter-view.coffee:136:26)
    at HTMLDivElement.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:16.4.0 markdown-preview-enhanced:toggle (input.hidden-input)
     -0:02.7.0 markdown-preview-enhanced:export-to-disk (div.slide)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "remote-atom",
      "fuzzy-finder",
      "atom-beautify",
      "browser-plus",
      "hyperclick",
      "ink"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.2.0 (active)
asciidoc-assistant, v0.2.1 (active)
asciidoc-image-helper, v1.0.0 (active)
asciidoc-preview, v2.7.1 (active)
atom-beautify, v0.29.16 (inactive)
atom-diary, v1.1.0 (inactive)
autocomplete-asciidoc, v0.1.1 (active)
autocomplete-java, v1.2.5 (inactive)
autocomplete-python, v1.8.26 (active)
dash, v1.7.0 (inactive)
gaia-dark-syntax, v2.0.0 (inactive)
goto-last-edit, v0.3.2 (active)
ink, v0.6.2 (inactive)
jekyll, v1.4.3 (inactive)
language-asciidoc, v1.7.0 (active)
language-liquid, v0.5.1 (active)
markdown-preview-enhanced, v0.9.2 (active)
proto-repl, v1.4.12 (active)
rainbow-tabs, v2.2.1 (active)
remote-edit, v1.8.24 (active)
script, v3.14.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (active)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
Hi @soulawaker , thanks for your reply,  
I will fix this issue today :)

**Comment by shd101wyy** [comment]
Yes it's a bug,
you can fix it temporarily by adding the following lines at the most top of your markdown file.  
```
---
presentation:
    enableSpeakerNotes: false
---
```  
I will let you know once I fix everything.

**Comment by shd101wyy** [comment]
Hi @soulawaker , this issue is fixed now. 
Thanks :)

**Comment by soulawaker** [comment]
Wow, It worked! Thanks!
