### ISSUE TITLE
Uncaught Error: Cannot find module 'loophole'

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#266]
[Enter steps to reproduce below:]

1.  ```cd markdown-preview-enhanced/```
2.  ```git pull wyy master```
3. ```restart ATOM```
4. ```open makedown file and enable preview```

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.9.6

### Stack Trace

Uncaught Error: Cannot find module 'loophole'

```
At module.js:457

Error: Cannot find module 'loophole'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/wangxu/Documents/github/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:10:21)
    at Object.<anonymous> (/Users/wangxu/Documents/github/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.startMDPreview (/Users/wangxu/Documents/github/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:123:35)
    at Object.toggle (/Users/wangxu/Documents/github/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:120:8)
    at atom-workspace.subscriptions.add.atom.commands.add.markdown-preview-enhanced:toggle (/Users/wangxu/Documents/github/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:31:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1136:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -0:00.1.0 markdown-preview-enhanced:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "nvatom",
      "save-autorun",
      "tree-view-finder",
      "Sublime-Style-Column-Selection",
      "platformio-ide-terminal"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "markdown-preview-enhanced": {
    "documentExportPath": "./exported",
    "exportPDFPageFormat": "A4",
    "imageFolderPath": "assets",
    "useGitHubStyle": true,
    "useGitHubSyntaxTheme": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-runner, v2.7.1 (inactive)
awiki, v0.3.1 (inactive)
console-panel, v0.2.0 (active)
git-time-machine, v1.5.3 (inactive)
markdown-mindmap, v0.2.4 (active)
markdown-preview-enhanced, v0.9.6 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
nvatom, v0.10.0 (inactive)
on-save, v0.2.9 (active)
platformio-ide-terminal, v2.0.10 (inactive)
save-autorun, v0.3.3 (inactive)
script, v3.10.1 (inactive)
script-runner, v1.8.4 (active)
Sublime-Style-Column-Selection, v1.5.1 (inactive)
tree-view-finder, v0.2.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (active)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (active)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
run `npm install` as well to install `loophole` package.

**Comment by xu4wang** [comment]
Thanks. 

Guess my installation is a little bit out dated. The problem was fixed after:
```
  sudo npm install loophole
  sudo npm install babyparse
```
