### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by shaohailong** [shd101wyy/markdown-preview-enhanced#27]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-markdown-katex](https://github.com/shd101wyy/atom-markdown-katex) package, v0.5.9

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:833

TypeError: Cannot read property 'split' of undefined
    at Function.module.exports.Range.fromText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:47:19)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:588:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:576:26
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:574:21)
    at TextBuffer.module.exports.TextBuffer.insert (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:607:19)
    at parseMD (/Users/lucas/.atom/packages/atom-markdown-katex/lib/md.js:368:16)
    at MarkdownPreview.renderMarkdown (/Users/lucas/.atom/packages/atom-markdown-katex/lib/md-preview.js:386:18)
    at MarkdownPreview.updateMarkdown (/Users/lucas/.atom/packages/atom-markdown-katex/lib/md-preview.js:376:10)
    at disposables.add.editor.onDidStopChanging (/Users/lucas/.atom/packages/atom-markdown-katex/lib/md-preview.js:168:16)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1378:25
```

### Commands

```
     -1:11.2.0 core:close (atom-pane.pane.active)
  2x -1:07.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:06.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:04.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -1:00.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:59.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:59.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:59.1.0 markdown-writer:toggle-h1 (atom-text-editor.editor)
     -0:56.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  5x -0:54.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:52.9.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:41.3.0 markdown-writer:insert-link (atom-text-editor.editor.mini)
     -0:28.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:25.3.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-one-dark-ui)
  6x -0:15.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.0 markdown-katex-preview:toc-create (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "typewriter-sounds",
      "file-icons",
      "emmet",
      "tidy-markdown"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "atom-markdown-katex": {
    "pdfOpenAutomatically": true,
    "useGitHubStyle": true,
    "useGitHubSyntaxTheme": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
atom-markdown-katex, v0.5.9
markdown-format, v2.5.1
markdown-image-helper, v1.0.4
markdown-writer, v2.3.3
pigments, v0.26.3

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
Hello @shaohailong , can you please write down the steps to reproduce the bug? 

Thank you very much ;)

**Comment by shd101wyy** [comment]
closing this issue now.
