### ISSUE TITLE
Uncaught Error: Cannot find module 'highlights.js'

### ISSUE THREAD

**Issue by joegnis** [shd101wyy/markdown-preview-enhanced#277]
[Enter steps to reproduce:]

1. Open a markdown file.
2. Toggle to open the markdown preview window.

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Fedora 25
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.9.8

### Stack Trace

Uncaught Error: Cannot find module '/usr/lib64/atom/node_modules/highlights/lib/highlights.js'

```
At module.js:457

Error: Cannot find module '/usr/lib64/atom/node_modules/highlights/lib/highlights.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/lib64/electron/1.3.13/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib64/atom/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/usr/lib64/atom/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced/lib/md.coffee:7:14)
    at /packages/markdown-preview-enhanced/lib/md.coffee:1:1)
    at Module._compile (/usr/lib64/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/usr/lib64/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib64/atom/src/native-compile-cache.js:50:27)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.initEvents (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:179:58)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:154:16
```

### Commands

```
     -3:38.7.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
markdown-preview-enhanced 0.9.8 
markdown-writer 2.6.3 
open-in-browser 0.4.7 
vim-mode-plus 0.82.2 
```

### Config

```
"*":
  core:
    disabledPackages: [
      "markdown-preview"
    ]
    telemetryConsent: "limited"
    themes: [
      "one-light-ui"
      "solarized-light-syntax"
    ]
  "exception-reporting":
    userId: "..."
  "markdown-preview-enhanced":
    openPreviewPaneAutomatically: false
  "markdown-writer":
    textStyles:
      italic:
        after: "_"
        before: "_"
  "spell-check": {}
  welcome: {}
```

**Comment by shd101wyy** [comment]
Hi @joegnis 
 
Try restarting your atom?

Thanks

**Comment by joegnis** [comment]
@shd101wyy 

I've tried restarting os and atom. Still the same.

**Comment by shd101wyy** [comment]
I don't really know why this happens.  
Could you please firstly upgrade your atom to 1.14.2, then reinstall this package?  
If this issue still happens, then it might be operating system related. As it works fine on my Mac.

**Comment by joegnis** [comment]
Alright, everything is working now after I installed the atom using the official package instead.

I used to install atom from this Fedora copr: [mosquito/atom Copr](https://copr.fedorainfracloud.org/coprs/mosquito/atom/). There must be a mix-up in it.

Thank you for your quick response.
