### ISSUE TITLE
matplotlib只显示第一象限的点

### ISSUE THREAD

**Issue by Jasper0819X** [shd101wyy/markdown-preview-enhanced#291]
代码如下：
```{python mpl:true, id:"izdlqdtc"}
# ```{python matplotlib:true, id:"izdlqdtc"}
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 20, 300)
plt.plot(x,np.sin(x))
plt.show()
```
运行后显示：
![image](https://cloud.githubusercontent.com/assets/15362491/23251751/692b6daa-f9e9-11e6-817c-64f1d382789c.png)

如果修改一下，变成`np.abs(np.sin(x))`的话：
![image](https://cloud.githubusercontent.com/assets/15362491/23251823/96e80fb4-f9e9-11e6-945a-7a8e8af60e8f.png)

这样就能绘制出来。
如果把范围从[0, 20]改成[-10, 10]：
![image](https://cloud.githubusercontent.com/assets/15362491/23251909/daba73c6-f9e9-11e6-815a-713b43d55610.png)
就又不行了

Windows版本：10.0.14393 x64
Python版本：3.6.0 x64
Atom版本：1.14.3 x64

**Comment by shd101wyy** [comment]
Hi @Jasper0819X ,

我没有遇到这个问题，可能是你的库的版本太低？升级下试试。    
还有你现在这种写法运行的是 python2，如果要运行 python3，应该写成  
<code>\`\`\`{python cmd:"python3"}</code>
![screen shot 2017-02-23 at 5 15 27 pm](https://cloud.githubusercontent.com/assets/1908863/23283483/c0afb98a-f9eb-11e6-9eef-2a2295a82044.png)

**Comment by Jasper0819X** [comment]
我系统里只装了Python3额，加上cmd:"python3"之后运行提示：
>'python3' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

这是我系统运行这两个命令的截图：
![image](https://cloud.githubusercontent.com/assets/15362491/23284797/6b592066-fa68-11e6-993b-851b079e7731.png)

matplotlib昨天才用pip装的。
另外如果我改一下变成cmd:"py"的话，可以画出图来，不过是出现一个单独的窗口：
![image](https://cloud.githubusercontent.com/assets/15362491/23284765/323be5b6-fa68-11e6-91f6-1c18628c96c0.png)

**Comment by Jasper0819X** [comment]
我把Python安装目录下面的python.exe复制了一份改成python3.exe，再执行就没出现“'python3' could not be spawned.”的错误，不过结果是和第一条comment里的情况一样的。

**Comment by shd101wyy** [comment]
哦你把 ` python3` 的路径系统设置成了 `python`。
然后我试了下 python3，确实是有问题，我的也是返回了白色的图像。。。😂    
看来 python2 是没问题的。  
我 `matplotlib:true` 其实就是在前面添加了以下的代码 
```python
# modify default matplotlib pyplot show function
try:
    import matplotlib
    matplotlib.use('Agg') # use Agg backend
    import matplotlib.pyplot as plt
    import sys
    def new_plt_show():
        plt.savefig(sys.stdout, format="svg")
    plt.show = new_plt_show # override old one
except Exception:
    pass
```
最近有点忙，我有时间再研究。你如果知道为啥将会这样是坠吼滴！

**Comment by shd101wyy** [comment]
还有你如果想要代码块也有高亮的话可是尝试下这个  
[language-gfm-enhanced](https://atom.io/packages/language-gfm-enhanced)

**Comment by Jasper0819X** [comment]
渲染出来的svg有错误：
```
Traceback (most recent call last):
  File "E:\Notebook\8g95jusss_code_chunk", line 29, in <module>
    plt.show()
  File "E:\Notebook\8g95jusss_code_chunk", line 8, in new_plt_show
    plt.savefig(sys.stdout, format="svg")
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\figure.py", line 1572, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\backend_bases.py", line 2244, in print_figure
    **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\backends\backend_svg.py", line 1212, in print_svg
    result = self._print_svg(filename, svgwriter, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\backends\backend_svg.py", line 1248, in _print_svg
    self.figure.draw(renderer)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\axes\_base.py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\axis.py", line 1141, in draw
    tick.draw(renderer)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\axis.py", line 264, in draw
    self.label1.draw(renderer)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\text.py", line 802, in draw
    ismath=ismath, mtext=mtext)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\backends\backend_svg.py", line 1164, in draw_text
    self._draw_text_as_path(gc, x, y, s, prop, angle, ismath, mtext)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\backends\backend_svg.py", line 897, in _draw_text_as_path
    writer.comment(s)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\backends\backend_svg.py", line 166, in comment
    self.__write("<!-- %s -->\n" % escape_comment(comment))
UnicodeEncodeError: 'gbk' codec can't encode character '\u2212' in position 5: illegal multibyte sequence
```

所以只要渲染出来的图里存在\u2212也就是负号的话就不行了。
但是sys.getdefaultencoding()结果是utf-8，很奇怪这里要转成gbk。可能是matplotlib的bug？
不过savefig('a.svg')是正常的。有没有办法先把图保存到一个临时文件，然后再读这个文件内容显示到页面里去的办法？

**Comment by shd101wyy** [comment]
我今天又试了一下 python3，莫名其妙的没有问题了。

**Comment by Jasper0819X** [comment]
解决方法在这里：
https://segmentfault.com/a/1190000005144275
