### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by ttasovac** [shd101wyy/markdown-preview-enhanced#302]
[Enter steps to reproduce:]

1. Open Markdown File
2. Toggle Markdown Preview 

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.10.1

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/ttasovac/.atom/packages/markdown-preview-enhanced/node_modules/ajv/lib/compile/index.js:171

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Ajv.localCompile (/packages/markdown-preview-enhanced/node_modules/ajv/lib/compile/index.js:139:26)
    at Ajv.resolve (/packages/markdown-preview-enhanced/node_modules/ajv/lib/compile/resolve.js:53:19)
    at Object.resolveRef (/packages/markdown-preview-enhanced/node_modules/ajv/lib/compile/index.js:210:21)
    at /packages/markdown-preview-enhanced/node_modules/ajv/lib/dotjs/ref.js:22:22)
    at /packages/markdown-preview-enhanced/node_modules/ajv/lib/dotjs/validate.js:156:37)
    at /packages/markdown-preview-enhanced/node_modules/ajv/lib/dotjs/properties.js:199:26)
    at generate_validate (/packages/markdown-preview-enhanced/node_modules/ajv/lib/dotjs/validate.js:229:37)
    at localCompile (/packages/markdown-preview-enhanced/node_modules/ajv/lib/compile/index.js:99:22)
    at Ajv.compile (/packages/markdown-preview-enhanced/node_modules/ajv/lib/compile/index.js:67:13)
    at _compile (/packages/markdown-preview-enhanced/node_modules/ajv/lib/ajv.js:328:29)
    at getSchema (/packages/markdown-preview-enhanced/node_modules/ajv/lib/ajv.js:192:51)
    at validate (/packages/markdown-preview-enhanced/node_modules/ajv/lib/ajv.js:91:11)
    at validateSchema (/packages/markdown-preview-enhanced/node_modules/ajv/lib/ajv.js:162:19)
    at _addSchema (/packages/markdown-preview-enhanced/node_modules/ajv/lib/ajv.js:288:7)
    at addSchema (/packages/markdown-preview-enhanced/node_modules/ajv/lib/ajv.js:133:26)
    at addInitialSchemas (/packages/markdown-preview-enhanced/node_modules/ajv/lib/ajv.js:396:39)
    at /packages/markdown-preview-enhanced/node_modules/ajv/lib/ajv.js:78:3)
    at /packages/markdown-preview-enhanced/node_modules/request/node_modules/har-validator/lib/node4/promise.js:43:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced/node_modules/request/lib/har.js:5:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced/node_modules/request/request.js:25:31)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced/node_modules/request/index.js:144:19)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced/lib/code-chunk.coffee:5:11)
    at /packages/markdown-preview-enhanced/lib/code-chunk.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced/lib/pandoc-convert.coffee:9:16)
    at /packages/markdown-preview-enhanced/lib/pandoc-convert.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:17:17)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.startMDPreview (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:129:35)
    at Object.toggle (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:126:8)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:31:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:14.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:05.8.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
atom-runner 2.7.1 
atom-wrap-in-tag 0.6.0 
autocomplete-modules 1.6.7 
document-outline 1.1.3 
existdb 0.4.1 
file-icons 2.0.17 
git-plus 7.3.3 
hyperclick 0.0.40 
language-blade 0.28.1 
language-nginx 0.6.2 
language-powershell 4.0.0 
laravel 0.7.1 
linter 1.11.23 
linter-php 1.3.1 
markdown-pdf 1.5.0 
markdown-preview-enhanced 0.10.1 
markdown-writer 2.6.4 
nord-atom-ui 0.10.1 
pdf-view 0.55.0 
pigments 0.39.0 
project-manager 3.3.3 
sync-settings 0.8.1 
todo-show 1.11.0 
tool-bar 1.0.1 
tool-bar-markdown-writer 0.2.0 
```

**Comment by shd101wyy** [comment]
Hi @ttasovac ,  

How did you trigger this issue?

Thanks

**Comment by ttasovac** [comment]
[Enter steps to reproduce:]

1. Open Markdown File
2. Toggle Markdown Preview

i.e. just tried to show the preview, nothing else.

**Comment by shd101wyy** [comment]
Can I have the content of your markdown file?

**Comment by shd101wyy** [comment]
Oh this seems to be `request` library issue. [#303](https://github.com/shd101wyy/markdown-preview-enhanced/issues/303#issuecomment-284139242) This guy gets the same problem.  
I will release a new version as soon as possible to fix it.  
Thanks

**Comment by shd101wyy** [comment]
I have just published a new version. Hope this issue is fixed.

**Comment by ttasovac** [comment]
Yes. Thanks a lot for your super quick attention to this.
I am now getting a different error (already reported in #306) but the error in this thread has been fixed.
Many thanks again!

**Comment by shd101wyy** [comment]
@ttasovac hi should be fixed now.  
Thanks
