### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by RogerChern** [shd101wyy/markdown-preview-enhanced#306]
[Enter steps to reproduce:]

1. Open abitrary markdown file.
2. Use shortcut to toggle the plugin.
3. The plugin reports error, and the rendered preview has no style with it.

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.10.3

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At C:\Users\Roger\.atom\packages\markdown-preview-enhanced\lib\style.coffee:63

ReferenceError: path is not defined
    at loadPreviewTheme (/packages/markdown-preview-enhanced/lib/style.coffee:63:23)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:175:9
    at Config.module.exports.Config.observeKeyPath (/app.asar/src/config.js:616:7)
    at Config.module.exports.Config.observe (/app.asar/src/config.js:141:21)
    at Object.appendGlobalStyle (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:173:38)
    at Object.startMDPreview (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:138:8)
    at Object.toggle (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:128:8)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:33:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:15.8.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
language-gfm-enhanced 0.90.0 
markdown-preview-enhanced 0.10.3 
sync-settings 0.8.1 
wordcount 2.10.4 
```

**Comment by wgwang** [comment]
I met this issue too.

**Comment by coolboy0961** [comment]
me too.

**Comment by wgwang** [comment]
solved this issue throught the following code change of the file "/packages/markdown-preview-enhanced/lib/style.coffee":


```javascript
  1   themes = atom.themes.getLoadedThemes()
59    path = require 'path'                                                                                                                                              
  1 
  2   for theme in themes
```

**Comment by shd101wyy** [comment]
@wgwang @RogerChern @wgwang my bad, should be fixed now.  
It is odd that this error didn't pop up in developer mode so I didn't notice it.
