### ISSUE TITLE
new themes don't work well

### ISSUE THREAD

**Issue by StefanoCecere** [shd101wyy/markdown-preview-enhanced#307]
after installing and selecting octocat-syntax the first time i open the preview i get this error:
from the second time i get my default one-dark theme! (so i can't get the github style white preview like before! :(

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.10.3

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Users/krur/.atom/packages/markdown-preview-enhanced/lib/style.coffee:63

ReferenceError: path is not defined
    at loadPreviewTheme (/packages/markdown-preview-enhanced/lib/style.coffee:63:23)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:175:9
    at Config.module.exports.Config.observeKeyPath (/app.asar/src/config.js:616:7)
    at Config.module.exports.Config.observe (/app.asar/src/config.js:141:21)
    at Object.appendGlobalStyle (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:173:38)
    at Object.startMDPreview (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:138:8)
    at Object.toggle (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:128:8)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:33:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:105:19)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:69:7)
```

### Commands

```
     -0:15.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:10.6.0 markdown-preview-enhanced:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-mermaid 3.0.0 
docblockr 0.9.1 
duplicate-removal 0.1.3 
file-icons 2.0.17 
flex-tool-bar 0.11.0 
hyperclick 0.0.40 
hyperclick-markdown 0.2.2 
jekyll 1.4.3 
language-gfm-enhanced 0.90.0 
language-ink 0.1.0 
language-liquid 0.5.1 
language-lua 0.9.11 
language-todotxt 0.6.1 
linter 1.11.23 
linter-php 1.3.1 
markdown-document 0.2.1 
markdown-preview-enhanced 0.10.3 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.6.4 
marked 0.1.10 
minimap 4.26.8 
octocat-syntax 1.3.1 
open-recent 5.0.0 
open-terminal-here 2.3.0 
open-unsupported-files 1.0.19 
php-twig 4.0.0 
project-manager 3.3.3 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.3 
tablr 1.8.1 
tasks 2.6.6 
todo-show 1.11.0 
tool-bar 1.0.1 
tool-bar-main 0.0.10 
uniq-line 0.0.2 
wordcount 2.10.4 
Zen 0.16.4 
```

**Comment by shd101wyy** [comment]
@StefanoCecere my bad, should be fixed now
