### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by IOOOTAlan** [shd101wyy/markdown-preview-enhanced#313]
[Enter steps to reproduce:]

1. Create front-matter with output set to either "pdf_document" or "word_document"
2. Document contains PlantUML diagrams
3. Right click "Pandoc"
4. Exception occurs

Notes:
 - using pandoc version 1.13.2;
 - "Export to disk" works ok on the same documents where pandoc fails;
 - documents with no PlantUML diagrams are exported correctly by Pandoc

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: linux 4.4.50
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.10.6

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /home/alan/.atom/packages/markdown-preview-enhanced/lib/process-graphs.coffee:202

TypeError: Cannot read property '1' of null
    at /packages/markdown-preview-enhanced/lib/process-graphs.coffee:202:24
    at /packages/markdown-preview-enhanced/node_modules/async/dist/async.js:3686:9
    at eachOfArrayLike (/packages/markdown-preview-enhanced/node_modules/async/dist/async.js:940:9)
    at eachOf (/packages/markdown-preview-enhanced/node_modules/async/dist/async.js:990:5)
    at _parallel (/packages/markdown-preview-enhanced/node_modules/async/dist/async.js:3685:5)
    at /packages/markdown-preview-enhanced/node_modules/async/dist/async.js:3765:3)
    at processCodes (/packages/markdown-preview-enhanced/lib/process-graphs.coffee:278:9)
    at processGraphs (/packages/markdown-preview-enhanced/lib/process-graphs.coffee:40:10)
    at pandocConvert (/packages/markdown-preview-enhanced/lib/pandoc-convert.coffee:260:3)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.pandocDocumentExport (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1845:5)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:84:63)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1170:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:333:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:30.4.0 markdown-preview-enhanced:toggle (input.hidden-input)
     -0:06.4.0 markdown-preview-enhanced:pandoc-document-export (p.sync-line)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
git-gui 0.1.27 
language-ansible 0.2.1 
linter 1.11.23 
linter-ansible-linting 1.2.2 
linter-ansible-syntax 1.1.2 
markdown-preview-enhanced 0.10.6 
```

**Comment by shd101wyy** [comment]
Hi @IOOOTAlan , 

Can you attach your code snippet here?  

Thanks

**Comment by IOOOTAlan** [comment]
Hi @shd101wyy , here is an anonymized version of the original document which retains the issue at hand: 
[test.md.txt](https://github.com/shd101wyy/markdown-preview-enhanced/files/823949/test.md.txt).
While anonymizing it, I noticed that if I took out line 100 as it currently is, then the error stops occurring:
```
100  introdotto _singola emissione_.
```
I tried replacing it with some other text in italics but the issue disappeared.
Do you have any idea on how this can be the source of the issue? To me, that seems valid markdown syntax...

**Comment by IOOOTAlan** [comment]
Just updated to v.0.10.7: the pandoc export feature seems to work again, thanks!
What was the issue?

**Comment by shd101wyy** [comment]
Haha I actually don't know why. I just added an error handler at the line that caused the problem.

**Comment by IOOOTAlan** [comment]
I found that there's still a problem, though: if you look at the file produced by pandoc using the test file I attached before, you can see that the last graph (under the `Title3` section) is not rendered at all, leaving the PlantUML specification in plain sight.
Maybe this is a new issue unrelated to the one I reported initially.

**Comment by shd101wyy** [comment]
I will have a look when I am free. Thanks

**Comment by shd101wyy** [comment]
@IOOOTAlan Should be fixed now.  
Cheers :)

**Comment by IOOOTAlan** [comment]
Thanks!
