### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by myerandme** [shd101wyy/markdown-preview-enhanced#317]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.8.0

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:457

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.4/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced-0.8.0/lib/markdown-preview-enhanced-view.coffee:2:25)
    at /packages/markdown-preview-enhanced-0.8.0/lib/markdown-preview-enhanced-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.startMDPreview (/packages/markdown-preview-enhanced-0.8.0/lib/markdown-preview-enhanced.coffee:88:35)
    at Object.toggle (/packages/markdown-preview-enhanced-0.8.0/lib/markdown-preview-enhanced.coffee:85:8)
    at /packages/markdown-preview-enhanced-0.8.0/lib/markdown-preview-enhanced.coffee:23:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:01.8.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:19.6.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-shell-commands-master undefined 
simplified-chinese-menu 3.5.0 
atom-terminal-panel-master undefined 
markdown-preview-enhanced 0.8.0 
```

**Comment by shd101wyy** [comment]
Please upgrade this package

**Comment by myerandme** [comment]
@shd101wyy 我还碰到了这个问题，我下载了10.8版。
Uncaught Error: Cannot find module 'atom-space-pen-views'
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.10.8


### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:457

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced-master/lib/markdown-preview-enhanced-view.coffee:2:25)
    at /packages/markdown-preview-enhanced-master/lib/markdown-preview-enhanced-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.startMDPreview (/packages/markdown-preview-enhanced-master/lib/markdown-preview-enhanced.coffee:131:35)
    at Object.toggle (/packages/markdown-preview-enhanced-master/lib/markdown-preview-enhanced.coffee:128:8)
    at /packages/markdown-preview-enhanced-master/lib/markdown-preview-enhanced.coffee:33:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at Object.didConfirmSelection (/app.asar/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:301:20)
    at SelectListView.didClickItem (/app.asar/node_modules/atom-select-list/src/select-list-view.js:220:10)
    at ListItemView.onclick (/app.asar/node_modules/atom-select-list/src/select-list-view.js:156:33)
    at ListItemView.didClick (/app.asar/node_modules/atom-select-list/src/select-list-view.js:349:10)
```

### Commands

```
     -0:22.7.0 command-palette:toggle (div.panels)
     -0:14.6.0 markdown-preview-enhanced:toggle (div.panels)
```

### Non-Core Packages

```
atom-shell-commands-master undefined 
simplified-chinese-menu 3.5.0 
atom-terminal-panel-master undefined 
markdown-preview-enhanced 0.10.8 
my-package 0.0.0 
```

**Comment by shd101wyy** [comment]
重新安装下吧。我也不太清楚为啥会这样，估计是安装的时候依赖没被装上。
[#191](https://github.com/shd101wyy/markdown-preview-enhanced/issues/191)
