### ISSUE TITLE
TypeError: Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by rmokerone** [shd101wyy/markdown-preview-enhanced#321]
<img width="420" alt="bug_atom" src="https://cloud.githubusercontent.com/assets/3683271/23796786/be2c6a12-05d7-11e7-822d-3ee292341b5c.png">
<img width="586" alt="bug_mac" src="https://cloud.githubusercontent.com/assets/3683271/23796787/be2f78b0-05d7-11e7-8290-e45c46c0dfc7.png">
<img width="765" alt="bug" src="https://cloud.githubusercontent.com/assets/3683271/23796788/be33a21e-05d7-11e7-932f-2c7c2c378e50.png">

尝试在mac 上使用atom安装出现上述问题。

**Comment by shd101wyy** [comment]
Hi @rmokerone ,

我觉得可能是网络问题。你试试 command line 安装 `apm install markdown-preview-enhanced`。

谢谢

**Comment by MARTIMM** [comment]
Hi,
Looks as if this error shows the same problem. It looks like there is an undefined variable hanging around which get used at the wrong moment....

[Enter steps to reproduce below:]

1. Startup atom
2. Error shows immediately

**Atom Version**: 1.2.0
**System**: "Fedora release
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.10.1


### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at Object.module.exports.MarkdownPreviewEnhanced.activate (/home/marcel/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:22:81)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:170:19)
    at /usr/share/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:512:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:490:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-atom-api",
      "markdown-preview"
    ],
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
markdown-preview-enhanced, v0.10.1
plantuml-viewer, v0.7.1

# Dev
No dev packages
```

Thanks for this great tool/machinery/something ;-)
Marcel

**Comment by shd101wyy** [comment]
@MARTIMM that is because the version (1.2.0) of your atom is too old. You need to upgrade atom to the newest version (1.6.0) then upgrade this package.
