### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by elmagnificogi** [shd101wyy/markdown-preview-enhanced#349]
[Enter steps to reproduce:]
我也不知道为什么

新手用户，我自己的plantUML可以正常生成使用

在你的里面就会这么报错，然后提示我java路径没找到？？
'java' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

实际上我有java 我没找到可以配置路径的地方 所以问一下这个是上面问题？

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**:Win10
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.10.11

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:160

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:706:26)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at /packages/markdown-preview-enhanced/lib/puml.coffee:29:14)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:989:19
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.renderPlantUML (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:996:9)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.bindEvents (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:607:6)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:550:8
    at finalize (/packages/markdown-preview-enhanced/lib/md.coffee:1022:12)
    at MarkdownPreviewEnhancedView.parseMD (/packages/markdown-preview-enhanced/lib/md.coffee:1060:12)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.renderMarkdown (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:535:6)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.updateMarkdown (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:527:6)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:264:10
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:1371:25
```

### Commands

```
  3x -1:22.7.0 editor:newline (input.hidden-input)
     -1:19.6.0 core:paste (input.hidden-input)
  4x -1:18.4.0 core:move-left (input.hidden-input)
  2x -1:16.3.0 core:move-down (input.hidden-input)
     -0:30.7.0 editor:newline (input.hidden-input)
     -0:07.3.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
git-control 0.8.2 
language-markdown 0.20.0 
language-plantuml 0.2.0 
markdown-pdf 1.5.0 
markdown-preview-enhanced 0.10.11 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
pdf-view 0.57.0 
plantuml 0.1.2 
plantuml-preview 0.12.8 
plantuml-support undefined 
plantuml-viewer 0.7.1 
```

**Comment by elmagnificogi** [comment]
此问题取消，它自动好了，我完全不知道为什么

**Comment by elmagnificogi** [comment]
```plantuml
@startuml
package com.xu81.uml{
    class TestA {
        -String name
        +int id
    }

    class TestB extends TestA{
        -String desc
        +String getDesc()
        +void setDesc(String desc)
    }
}
@enduml
```
我用上面的这个代码

然后生成结果是：
Dot Executable: null
No dot executable found
Cannot find Graphviz. You should try
@startuml
testdot
@enduml
or
java -jar plantuml.jar -testdot

但如果是 这样简单的关系 就没有问题，只要一上类就出问题了
Bob -> Alice : Hello, how are you
Alice -> Bob : Fine, thank you, and you?

所以我能自己指定Graphviz的位置吗？ 设置里没有这个参数

**Comment by shd101wyy** [comment]
把 graphviz 设置成系统全局变量就好了

**Comment by elmagnificogi** [comment]
后来设置成全局可以了，不过plantuml相关的插件都给了设置路径的地方，要能提供的话，我感觉会挺好

**Comment by mritzco** [comment]
Hi, 
Getting the same issue on Windows 10 trying to render plantuml in 2 different laptops.

Is there a list of pre-requisites for the package to run? 
Would be great to have one if anything else is required.
