### ISSUE TITLE
Build this plugin as a command line tool

### ISSUE THREAD

**Issue by icearith** [shd101wyy/markdown-preview-enhanced#357]
Is it easy to wrap up this plugin into a atom independent command line tool so that I could convert markdown documents(contains mermaid scripts and viz scripts) to html documents?

**Comment by icearith** [comment]
@shd101wyy

**Comment by Flauschbaellchen** [comment]
Hi @shd101wyy 

I would really like to have this feature, too.
In my case I need not the HTML but PDF export function.

Currently I'm using your plugin to write documentation with graphs, task-lists etc. for a software I'm developing but always need to export the final PDF manually which is tedious.
Having the possibility to access those functions from outside would allow me to setup continuous integration to build the PDF on every commit.

Right now I'm trying to generate a Github-flowered Task List with Pandoc/LateX but currently it seems not be possible (or is very, very hacky: https://github.com/CDSoft/pp)
Using your plugin would be great as it also supports many other useful features like mermaid etc.

Is there a possibility to get access to any export function your plugin provides on a non-GUI shell?

**Comment by shd101wyy** [comment]
Hi @icearith @Flauschbaellchen 

So far I have just written a nodejs module called [MUME](https://github.com/shd101wyy/mume). I will support the command line export soon. 

Thanks

**Comment by Flauschbaellchen** [comment]
Hi @shd101wyy,

do you have any news on this topic?
I've looked into your other repo at https://github.com/shd101wyy/mume but did not get it to work.

Do you have a list of dependencies for every parser?
For pandoc I'm getting:
```root@2c1b12c3b785:/media# nodejs mume.js 
(node:310) UnhandledPromiseRejectionWarning: Output format needs to be specified.
(node:310) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:310) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
For phantomjs I'm getting:
```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at Pipe.onread (net.js:623:25)
```
Which node version do I need to have installed? I used the latest node version for my examples.
Maybe you have a minimal example using one of the docker containers for nodejs?

**Comment by shd101wyy** [comment]
Hi @Flauschbaellchen ,

For pandoc, you need to follow the same instructions as MPE.  You need to specify `output` in your front matter: https://shd101wyy.github.io/markdown-preview-enhanced/#/pandoc-pdf

For phantomjs, you need to have phantomjs installed globally first.  

Thanks
