### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by mancelee** [shd101wyy/markdown-preview-enhanced#390]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.12.0

### Stack Trace

Uncaught SyntaxError: Unexpected token < in JSON at position 0

```
At file:///C:/Users/Administrator/AppData/Local/atom/app-1.16.0/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (/packages/markdown-preview-enhanced/lib/sm.coffee:10:17)
    at Request.self.callback (/packages/markdown-preview-enhanced/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/markdown-preview-enhanced/node_modules/request/request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/markdown-preview-enhanced/node_modules/request/request.js:980:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:45.5.0 editor:delete-line (input.hidden-input)
     -2:45.1.0 intentions:highlight (input.hidden-input)
     -2:41.2.0 core:save (input.hidden-input)
     -2:38.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:32.3.0 intentions:highlight (input.hidden-input)
     -2:32 markdown-preview-enhanced:image-helper (input.hidden-input)
     -1:58.9.0 window:toggle-dev-tools (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -1:41.3.0 settings-view:open (div.markdown-preview-enhanced.native-key-bindings)
     -0:57.1.0 core:backspace (input.hidden-input)
     -0:50 window:toggle-dev-tools (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:40.9.0 intentions:highlight (input.hidden-input)
     -0:40.6.0 markdown-preview-enhanced:image-helper (input.hidden-input)
     -0:01.8.0 intentions:highlight (input.hidden-input)
     -0:01.6.0 editor:delete-line (input.hidden-input)
     -0:00.8.0 intentions:highlight (input.hidden-input)
  2x -0:00.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-html-preview 0.1.22 
atom-ternjs 0.18.2 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
color-picker 2.2.5 
docblockr 0.9.4 
file-icons 2.1.4 
git-plus 7.7.0 
intentions 1.1.2 
jquery-snippets 11.0.0 
language-gfm-enhanced 0.92.0 
linter 2.1.4 
linter-jshint 3.0.3 
linter-ui-default 1.2.3 
markdown-preview-enhanced 0.12.0 
minimap 4.28.1 
platformio-ide-terminal 2.5.0 
script 3.14.1 
split-diff 1.3.0 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
```

**Comment by shd101wyy** [comment]
@mancelee can I see your markdown file?

**Comment by shd101wyy** [comment]
Oh I see, `sm.ms` api changed.

**Comment by shd101wyy** [comment]
seems that `sm.ms` website is done.

**Comment by mancelee** [comment]
是的，确实挂掉了，现在只提供这个两个图床吗，国内访问好慢

**Comment by shd101wyy** [comment]
是的现在只支持这两个。    
有人向我推荐 qiniu，我有时间了再研究下吧 :)

**Comment by ToSeven** [comment]
求支持七牛 两个都挂了。。。。。

**Comment by ToSeven** [comment]
不对 sm.ms没挂 国内可以访问

**Comment by shd101wyy** [comment]
不知道为啥会这样，原来使用着还没有问题。    
[sm.coffee](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/lib/sm.coffee)    
我有时间了再研究下吧。

**Comment by shd101wyy** [comment]
@ToSeven @mancelee 修好了。谢谢～
