### ISSUE TITLE
Uncaught TypeError: define is not a function

### ISSUE THREAD

**Issue by ycjeanlin** [shd101wyy/markdown-preview-enhanced#405]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.12.3

### Stack Trace

Uncaught TypeError: define is not a function

```
At C:\Users\yzl00\.atom\packages\markdown-preview-enhanced\dependencies\save-svg-as-png\save-svg-as-png.js:330

TypeError: define is not a function
    at /packages/markdown-preview-enhanced/dependencies/save-svg-as-png/save-svg-as-png.js:330:5
    at /packages/markdown-preview-enhanced/dependencies/save-svg-as-png/save-svg-as-png.js:334:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced/lib/pandoc-convert.coffee:9:17)
    at /packages/markdown-preview-enhanced/lib/pandoc-convert.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:19:19)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.startMDPreview (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:131:35)
    at Object.toggle (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:128:8)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:33:47)
```

### Commands

```
     -1:17.7.0 markdown-preview:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:28.8.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
markdown-preview-enhanced 0.12.3 
```

**Comment by shd101wyy** [comment]
Hi @ycjeanlin 

How did you trigger this issue?

Thanks
