### ISSUE TITLE
Uncaught TypeError: Cannot read property 'level' of undefined

### ISSUE THREAD

**Issue by artbrock** [shd101wyy/markdown-preview-enhanced#406]
[Enter steps to reproduce:]

1. ... I was editing section headings on the page (promoting them by removing one leading "#")
2. ... Then I updated the TOC "depthfrom" index from 3 to 2

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.12.3

### Stack Trace

Uncaught TypeError: Cannot read property 'level' of undefined

```
At /home/artbrock/.atom/packages/markdown-preview-enhanced/lib/toc.coffee:75

TypeError: Cannot read property 'level' of undefined
    at toc (/packages/markdown-preview-enhanced/lib/toc.coffee:75:28)
    at updateTOC (/packages/markdown-preview-enhanced/lib/md.coffee:826:21)
    at finalize (/packages/markdown-preview-enhanced/lib/md.coffee:1086:43)
    at MarkdownPreviewEnhancedView.parseMD (/packages/markdown-preview-enhanced/lib/md.coffee:1156:12)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.renderMarkdown (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:537:6)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.updateMarkdown (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:529:6)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:266:10
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:1392:25
```

### Commands

```
     -0:42.4.0 core:cut (input.hidden-input)
     -0:40.2.0 editor:newline (input.hidden-input)
     -0:39.8.0 core:paste (input.hidden-input)
     -0:38.9.0 editor:newline (input.hidden-input)
  6x -0:37.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
markdown-preview-enhanced 0.12.3 
```

**Comment by shd101wyy** [comment]
Thx! I will get it fixed next week

**Comment by shd101wyy** [comment]
@artbrock Should be fixed now :)

Thanks
