### ISSUE TITLE
Uncaught SyntaxError: Unexpected token , in JSON at position 28

### ISSUE THREAD

**Issue by zrhans** [shd101wyy/markdown-preview-enhanced#411]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: linux 4.10.13-1-ARCH
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.12.3

### Stack Trace

Uncaught SyntaxError: Unexpected token , in JSON at position 28

```
At file:///usr/share/atom/resources/app/static/index.html:1

SyntaxError: Unexpected token , in JSON at position 28
    at Object.parse (native)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:52:34)
    at Object.startMDPreview (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:134:21)
    at Object.toggle (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:128:8)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:33:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:1)
    at /usr/share/atom/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:11.8.0 intentions:highlight (input.hidden-input)
     -0:11.5.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-markdown-auto-preview 1.1.1 
atom-terminal 0.8.0 
busy-signal 1.4.1 
gfm-pdf 0.3.4 
intentions 1.1.2 
language-fortran 2.1.0 
linter 2.1.4 
linter-markdown 4.0.1 
linter-ui-default 1.5.4 
markdown-preview-enhanced 0.12.3 
markdown-scroll-sync 2.1.2 
markdown-table-editor 0.5.1 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
pdf-view 0.58.0 
terminal-fusion 2.4.4 
```

**Comment by shd101wyy** [comment]
Hi @zrhans , that means your configuration is wrong.  
I can see your settings for math block indicators?  
Thanks

**Comment by zrhans** [comment]
I think the problem was solved. To be honest I did not saw that this issue was created. Sorry. It seems that all the blocks are working perfectly. The package is fine and very handy.

**Comment by shd101wyy** [comment]
Great. I will close this issue then :)
