### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by andersab** [shd101wyy/markdown-preview-enhanced#423]
[Enter steps to reproduce:]

1. Create a new markdown file 
2. Add 
```plantuml
@startuml

@enduml

```

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.12.5

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:160

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:286:12)
    at PlantUMLTask.generateSVG (/packages/markdown-preview-enhanced/lib/puml.coffee:39:17)
    at Object.render (/packages/markdown-preview-enhanced/lib/puml.coffee:59:28)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1082:19
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.renderPlantUML (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1092:9)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.bindEvents (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:680:6)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:575:8
    at finalize (/packages/markdown-preview-enhanced/lib/md.coffee:1149:14)
    at MarkdownPreviewEnhancedView.parseMD (/packages/markdown-preview-enhanced/lib/md.coffee:1189:12)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.renderMarkdown (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:560:6)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.updateMarkdown (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:552:6)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:298:10
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1442:1
```

### Commands

```
     -3:43.2.0 command-palette:toggle (div.package-detail.panels-item)
  2x -3:39.6.0 core:move-down (input.hidden-input)
     -3:37.7.0 core:confirm (input.hidden-input)
     -3:37.7.0 sync-settings:restore (div.package-detail.panels-item)
     -2:24.4.0 core:backspace (input.hidden-input)
     -2:18.6.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:01.2.0 intentions:highlight (input.hidden-input)
     -1:01.1.0 application:new-file (input.hidden-input)
     -1:00.0 intentions:highlight (input.hidden-input)
     -0:42.2.0 command-palette:toggle (input.hidden-input)
     -0:40.7.0 editor:consolidate-selections (input.hidden-input)
     -0:40.7.0 core:cancel (input.hidden-input)
     -0:39.6.0 intentions:highlight (input.hidden-input)
     -0:38 settings-view:open (input.hidden-input)
     -0:20.3.0 markdown-preview-enhanced:toggle (input.hidden-input)
  2x -0:14.4.0 vim-mode-plus:move-up (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.26 
atom-material-ui 2.0.4 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.7 
git-plus 7.9.2 
highlight-selected 0.13.1 
intentions 1.1.2 
language-ansible 0.2.1 
language-cassandra-cql 0.1.2 
language-docker 1.1.8 
language-gradle 0.0.3 
language-plantuml 0.2.0 
linter 2.1.4 
linter-gcc 0.7.1 
linter-ui-default 1.6.0 
markdown-preview-enhanced 0.12.5 
monokai 0.24.0 
nucleus-dark-ui 0.12.3 
pigments 0.39.1 
plantuml-viewer 0.7.1 
python-indent 1.0.2 
python-tools 0.6.9 
react 0.16.2 
remote-edit 1.9.0 
seti-ui 1.8.0 
sync-settings 0.8.1 
tabs-to-spaces 1.0.3 
terminal-plus 0.14.5 
todo-show 1.11.0 
vagrant 0.1.0 
vim-mode-plus 0.93.0 
vim-mode-plus-ex-mode 0.9.1 
```

**Comment by shd101wyy** [comment]
Does restating atom help? Or this issue still happened even after you restart?

**Comment by andersab** [comment]
No, restarting did not help.

**Comment by andersab** [comment]
It started working before the last update, it appears it was removed during the most recent.
