### ISSUE TITLE
取消welcome 自动打开

### ISSUE THREAD

**Issue by staostd** [shd101wyy/markdown-preview-enhanced#428]
您好，请问能否取消一打开Atom就自动打开 markdown preview enhanced 的welcome 文档呢？

**Comment by shd101wyy** [comment]
应该只会打开一次才对，难道每次都会打开吗？

**Comment by staostd** [comment]
是的哎，我的每次都打开。

**Comment by shd101wyy** [comment]
哦还真是，我晚上修一下，抱歉。

**Comment by staostd** [comment]
没关系，谢谢您！package非常实用！

**Comment by shd101wyy** [comment]
@staostd  修好了，现在会每当这个插件更新后才会弹出来一次。

非常抱歉发生这个问题

**Comment by tzing** [comment]
您好
我這邊的狀況是在更新 `0.12.7` 之後反而發生一點狀況

每次開啟atom依然會跳出 `WELCOME.md` ，並跳出alert
目前嘗試markdown preview enhanced的功能似乎都還正常，不太確定這個alert本身有沒有其他影響

以下為atom產生的訊息

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: ~Unknown Windows version~ Windows 10 Education
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.12.7


### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At fs is not defined

ReferenceError: fs is not defined
    at helper (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:135:7)
    at Object.openWelcomePage (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:142:7)
    at Object.activate (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:127:6)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:253:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:600:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/atom-environment.js:832:1
```

### Non-Core Packages

```
atom-jinja2 0.6.0 
kite 0.26.0 
language-batch 0.4.0 
language-doxygen 0.2.1 
language-gradle 0.0.3 
language-matlab 0.2.1 
language-restructuredtext 1.1.0 
language-shadercode-shaderlab 2.0.1 
language-tex 0.4.0 
MagicPython 1.0.10 
markdown-folder 0.5.0 
markdown-pdf 1.5.0 
markdown-preview-enhanced 0.12.7 
platformio-ide-terminal 2.5.1 
sync-settings 0.8.1 
unity-shader-files 0.3.0 
```

**Comment by shd101wyy** [comment]
@tzing 我的锅，修好了。谢谢 :)

**Comment by tzing** [comment]
@shd101wyy 您辛苦了!

**Comment by shd101wyy** [comment]
客气客气
