### ISSUE TITLE
升级到0.12.7后还是每次打开welcome页面，并且会出现fs is not define的错误

### ISSUE THREAD

**Issue by coolboy0961** [shd101wyy/markdown-preview-enhanced#431]
![previewbug](https://cloud.githubusercontent.com/assets/12973893/26750964/6fb52110-4869-11e7-9544-5d1379616bcf.gif)

我用的package的安装方式是下载zip，然后替换原有的markdown-preview-enhanced文件夹，因为我用atom总是无法显示出有markdown-preview-enhanced的更新。

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.12.7

### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At fs is not defined

ReferenceError: fs is not defined
    at helper (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:135:7)
    at Object.openWelcomePage (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:142:7)
    at Object.activate (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:127:6)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.29.26 
atom-csv-markdown 1.0.2 
atom-html-preview 0.1.22 
atom-mermaid 3.1.0 
atom-ternjs 0.18.3 
autocomplete-java 1.2.7 
codic 0.1.0 
git-log 0.4.1 
goto-definition 1.3.3 
language-diff 0.7.0 
language-gfm-enhanced 0.92.0 
language-plantuml 0.2.0 
markdown-mindmap 0.3.3 
markdown-preview-enhanced 0.12.7 
markdown-table-editor 0.5.2 
markdown-table-formatter 2.9.0 
markdown-themeable-pdf 1.2.0 
plantuml-viewer 0.7.1 
script 3.15.0 
symbols-tree-view 0.14.0 
tablr 1.8.3 
```

**Comment by shd101wyy** [comment]
我的，修好了

**Comment by coolboy0961** [comment]
好快！
好用了，非常感谢。
