### ISSUE TITLE
Uncaught TypeError: editor.getPath is not a function

### ISSUE THREAD

**Issue by brianryer** [shd101wyy/markdown-preview-enhanced#451]
[Enter steps to reproduce:]

1. Open a markdown file
2. Attempt to preview

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.13.0

### Stack Trace

Uncaught TypeError: editor.getPath is not a function

```
At /Users/brian/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:194

TypeError: editor.getPath is not a function
    at Object.startMDPreview (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:194:91)
    at Object.toggle (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:182:8)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:41:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:35.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:07.5.0 markdown-preview-enhanced:toggle (div.tool-panel.tree-view)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.10.2 
asciidoctor-preview 0.3.2 
atom-beautify 0.29.26 
atom-formatter-jsbeautify 1.1.2 
atom-html-preview 0.1.22 
atom-mermaid 3.1.0 
atom-xsltransform 0.8.0 
autocomplete 0.47.0 
autocomplete-asciidoc 0.1.2 
autocomplete-xml 0.9.4 
busy-signal 1.4.3 
emmet 2.4.3 
emmet-simplified 2.5.0 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.7 
graphviz-preview-plus 1.4.2 
hey-pane 1.0.0 
hyperclick 0.0.40 
intentions 1.1.2 
language-asciidoc 1.10.0 
language-dot 1.7.0 
language-markdown 0.23.0 
language-mermaid 0.6.0 
lines 0.13.1 
lint 0.0.1 
linter 2.1.4 
linter-alex 4.0.0 
linter-csslint 1.3.4 
linter-just-say-no 0.7.3 
linter-markdown 4.0.1 
linter-ui-default 1.6.1 
linter-write-good 0.9.0 
markdown-document 0.2.1 
markdown-folder 0.5.0 
markdown-preview-enhanced 0.13.0 
markdown-writer 2.6.5 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
one-o-eight-syntax 0.28.2 
pigments 0.39.1 
project-manager 3.3.5 
project-plus 1.0.0 
project-view 0.6.2 
project-viewer 1.1.2 
promote-folder-to-project 2.0.1 
red-wavy-underline 0.3.3 
simple-drag-drop-text 0.3.4 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.2 
tasks 2.6.6 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tool-bar-markdown-writer 0.3.0 
tree-view-autoresize 2.1.0 
tree-view-filter 0.5.3 
tree-view-open-files 0.3.0 
tree-view-sort 0.7.0 
unity-dark-ui 2.0.9 
unity-ui 2.1.11 
```

**Comment by shd101wyy** [comment]
Hi. Does restarting atom help?

**Comment by brianryer** [comment]
Yes, in fact, just waiting for all of the packages to finish initializing fixes it, as far as I can tell.

**Comment by shd101wyy** [comment]
Great. I will close this issue then.
