### ISSUE TITLE
@import .md File with TOC Crashes

### ISSUE THREAD

**Issue by jasonhenderson** [shd101wyy/markdown-preview-enhanced#452]
Steps to reproduce:
1. Create .md file and add TOC through Atom helper, e.g. "Test1.md"
1. Create another .md file with a TOC added through helper, e.g. "Test2.md"
1. add @import "Test2.md" to the bottom of Test1.md

You will get a bunch of these in your plugin console:

```
<embedded>:71406 Uncaught (in promise) TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1071:26)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:564:29)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:554:32
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:849:24)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:552:27)
    at updateTOC (/Users/[redacted]/.atom/packages/markdown-preview-enhanced/lib/md.coffee:835:16)
    at finalize (/Users/[redacted]/.atom/packages/markdown-preview-enhanced/lib/md.coffee:1061:45)
    at /Users/[redacted]/.atom/packages/markdown-preview-enhanced/lib/md.coffee:1114:14
```

**Comment by shd101wyy** [comment]
Hi @jasonhenderson ,  

Thanks a lot. Will be fixed in next version :)

**Comment by kachkaev** [comment]
@jasonhenderson is this still the case with the latest version of the plugin?
