### ISSUE TITLE
Uncaught TypeError: editor.getFileName is not a function

### ISSUE THREAD

**Issue by tanle8** [shd101wyy/markdown-preview-enhanced#453]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.13.0

### Stack Trace

Uncaught TypeError: editor.getFileName is not a function

```
At /Users/temp/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:226

TypeError: editor.getFileName is not a function
    at Object.checkValidMarkdownFile (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:226:27)
    at Object.startMDPreview (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:199:14)
    at Object.toggle (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:182:8)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:41:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -7:05.2.0 core:close (atom-pane.pane.active)
     -4:26.8.0 markdown-preview-enhanced:toggle (input.hidden-input)
     -2:45.2.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-monokai.theme-one-dark-ui)
     -0:15 markdown-preview-enhanced:toggle (div#linter-panel.)
```

### Non-Core Packages

```
atom-latex 0.7.11 
atom-monokai 0.10.9 
busy-signal 1.4.3 
intentions 1.1.2 
linter 2.1.4 
linter-eslint 8.2.1 
linter-markdown 4.0.1 
linter-pycodestyle 2.0.2 
linter-ui-default 1.6.1 
markdown-preview-enhanced 0.13.0 
minimap 4.28.2 
platformio-ide-terminal 2.5.1 
script 3.15.0 
```

**Comment by shd101wyy** [comment]
Hi @tanle8 , try restarting atom.

**Comment by jopernikus** [comment]
Hi, restarting does not work for me:
Atom 1.18.0 x64
OS: Mac OS X 10.12.5
Thrown From: markdown-preview-enhanced package 0.13.0
I still get the same as @tanle8 after closing all windows and quiting atom.
Restart atom with no windows open.
Open a project, click on markdown file, Select Packages - markdown-preview-enhanced - Toggle
The markdown-preview standard package is disabled.

**Comment by shd101wyy** [comment]
@tanle8 @jmatsushita I am assuming that you are trying to toggle preview for an untitled, unsaved markdown file? You will need to save your markdown file first. Then toggle preview.

**Comment by shd101wyy** [comment]
Yes [#226](https://github.com/shd101wyy/markdown-preview-enhanced/blob/master/lib/markdown-preview-enhanced.coffee#L226) should be:
 
```javascript
if !editor or !editor.getFileName?()
```
