### ISSUE TITLE
Getting this error message while creating new empty file

### ISSUE THREAD

**Issue by gepcel** [shd101wyy/markdown-preview-enhanced#486]
I kept getting this error message while creating new empty  file. The file hasn't been saved yet, thus just an empty tab named `untitled`.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.13.0

### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At C:\Users\way\.atom\packages\markdown-preview-enhanced\lib\markdown-preview-enhanced.coffee:212

TypeError: Cannot read property 'startsWith' of undefined
    at Object.getPreviewForEditor (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:212:29)
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:66:22
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.18.0/resources/app/src/workspace.js:493:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/workspace-center.js:16:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane-container.js:280:26)
    at Pane.module.exports.Pane.setActiveItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:318:22)
    at Pane.module.exports.Pane.activateItemAtIndex (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:454:25)
    at Pane.module.exports.Pane.activateNextItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:409:27)
    at atom-workspace.pane:show-next-item (~/AppData/Local/atom/app-1.18.0/resources/app/src/register-default-commands.js:24:54)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  4x -0:49.2.0 advanced-open-file:autocomplete (input.hidden-input)
     -0:43.3.0 core:confirm (input.hidden-input)
     -0:40.9.0 advanced-open-file:toggle (input.hidden-input)
  4x -0:37.9.0 advanced-open-file:autocomplete (input.hidden-input)
     -0:30.9.0 core:confirm (input.hidden-input)
     -0:29.1.0 advanced-open-file:toggle (input.hidden-input)
     -0:25.1.0 core:backspace (input.hidden-input)
  4x -0:24.4.0 advanced-open-file:autocomplete (input.hidden-input)
     -0:19.7.0 core:confirm (input.hidden-input)
     -0:16.3.0 core:close (input.hidden-input)
     -0:15 pane:show-next-item (input.hidden-input)
     -0:14.6.0 core:close (input.hidden-input)
     -0:14 pane:show-next-item (input.hidden-input)
     -0:13.5.0 core:close (input.hidden-input)
     -0:12.6.0 pane:show-next-item (input.hidden-input)
     -0:00.5.0 application:new-file (a.btn-copy-report.icon.icon-clippy)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.3 
atom-jinja2 0.6.0 
atom-material-syntax 1.0.6 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
autocomplete-python 1.9.1 
ex-mode 0.15.0 
expand-region 0.3.0 
flask-snippets 0.3.3 
gfm-pdf 0.3.4 
highlight-selected 0.13.1 
Hydrogen 1.19.0 
hydrogen-launcher 1.2.1 
kite 0.30.0 
language-gfm-enhanced 0.92.0 
markdown-preview-enhanced 0.13.0 
markdown-writer 2.6.5 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
open-recent 5.0.0 
platformio-ide-terminal 2.5.3 
symbols-tree-view 0.14.0 
sync-settings 0.8.2 
tidy-markdown 3.0.1 
vim-mode-plus 0.93.0 
wordcount 2.10.4 
```

**Comment by shd101wyy** [comment]
@gepcel Update this package and try again?

**Comment by gepcel** [comment]
Solved. Thank you.
