### ISSUE TITLE
Uncaught ReferenceError: filePath is not defined

### ISSUE THREAD

**Issue by v1-hermit** [shd101wyy/markdown-preview-enhanced#489]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.13.0

### Stack Trace

Uncaught ReferenceError: filePath is not defined

```
At C:\Users\yang\.atom\packages\markdown-preview-enhanced\lib\markdown-preview-enhanced-view.coffee:1961

ReferenceError: filePath is not defined
    at /packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1961:95
    at /packages/markdown-preview-enhanced/node_modules/async/dist/async.js:3861:9
    at /packages/markdown-preview-enhanced/node_modules/async/dist/async.js:421:16
    at iterateeCallback (/packages/markdown-preview-enhanced/node_modules/async/dist/async.js:924:17)
    at /packages/markdown-preview-enhanced/node_modules/async/dist/async.js:906:16
    at /packages/markdown-preview-enhanced/node_modules/async/dist/async.js:3858:13
    at ReadFileContext.callback (/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:1953:20)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
```

### Commands

```
     -4:00.6.0 core:backspace (input.hidden-input)
     -4:00.3.0 core:delete (input.hidden-input)
     -3:59.4.0 core:confirm (input.hidden-input)
     -1:27.2.0 markdown-preview-enhanced:toggle (div.line)
     -1:08.2.0 editor:newline (input.hidden-input)
     -1:07.9.0 core:move-up (input.hidden-input)
     -1:07.7.0 core:paste (input.hidden-input)
     -0:27.8.0 editor:newline (input.hidden-input)
     -0:27.6.0 core:paste (input.hidden-input)
     -0:21.7.0 core:save (input.hidden-input)
     -0:16.4.0 markdown-preview-enhanced:export-to-disk (div.markdown-preview-enhanced)
```

### Non-Core Packages

```
atom-mermaid 3.1.0 
simplified-chinese-menu 3.5.0 
language-markdown 0.23.0 
markdown-folder 0.5.0 
markdown-pdf 1.5.4 
markdown-preview-enhanced 0.13.0 
markdown-preview-opener 0.1.1 
markdown-preview-plus 2.4.10 
markdown-preview-plus-opener 0.2.0 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
mathjax-wrapper 0.1.0 
open-in-browser 0.5.2 
open-in-browsers 0.0.30 
```

**Comment by v1-hermit** [comment]
没人管了？

**Comment by shd101wyy** [comment]
最近在写 vscode 版本，atom 的得往后放放。  
晚安

**Comment by shd101wyy** [comment]
Hi @v1-hermit ，应该没问题了。
