### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroyItem' of undefined

### ISSUE THREAD

**Issue by jacobvv** [shd101wyy/markdown-preview-enhanced#523]
[Enter steps to reproduce:]

1. Open atom
2. Open a markdown file named "setup.md"
3. Ctrl + Shift + P, choose "markdown preview enhanced: toggle" than error occur.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.14.3

### Stack Trace

Uncaught TypeError: Cannot read property 'destroyItem' of undefined

```
At /home/jacob/.atom/packages/markdown-preview-enhanced/out/src/extension.js:86

TypeError: Cannot read property 'destroyItem' of undefined
    at /packages/markdown-preview-enhanced/out/src/extension.js:86:13)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -4:21.7.0 core:paste (input.hidden-input)
     -4:20.5.0 core:save (input.hidden-input)
     -3:05.4.0 markdown-writer:insert-new-line (input.hidden-input)
     -3:05.4.0 editor:newline (input.hidden-input)
     -3:05.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -3:05.3.0 editor:newline (input.hidden-input)
     -3:05.0 core:paste (input.hidden-input)
     -3:03.7.0 core:save (input.hidden-input)
     -0:27.9.0 command-palette:toggle (input.hidden-input)
 17x -0:22.2.0 core:backspace (input.hidden-input)
     -0:18.9.0 core:confirm (input.hidden-input)
     -0:18.9.0 markdown-preview-enhanced:toggle (input.hidden-input)
     -0:15.9.0 command-palette:toggle (input.hidden-input)
     -0:14.1.0 core:confirm (input.hidden-input)
     -0:14.1.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
autocomplete-python 1.9.1 
color-picker 2.2.5 
highlight-selected 0.13.1 
hyperclick 0.1.2 
markdown-preview-enhanced 0.14.3 
markdown-writer 2.6.5 
minimap 4.29.0 
minimap-git-diff 4.3.1 
pigments 0.39.1 
platformio-ide-terminal 2.5.3 
```

**Comment by shd101wyy** [comment]
Does restarting atom help?

**Comment by jacobvv** [comment]
year it worked, thanks a lot.

**Comment by shd101wyy** [comment]
So I will close this issue for now. You can reopen it if you see it again.
