### ISSUE TITLE
Uncaught TypeError: Cannot read property '25' of undefined

### ISSUE THREAD

**Issue by miskovics** [shd101wyy/markdown-preview-enhanced#560]
Steps to reproduce:

1. Click on a checked or unchecked checkbox in `preview` pane.
2. Nothing happens in `preview` page (checkbox stays as it was), exception is thrown.
    Expected behavior: Checkbox state is changed in `preview` pane and source, no exception is thrown ;-)

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.14.6

### Stack Trace

Uncaught TypeError: Cannot read property '25' of undefined

```
At C:\Users\g\.atom\packages\markdown-preview-enhanced\out\src\preview-content-provider.js:788

TypeError: Cannot read property '25' of undefined
    at MarkdownPreviewEnhancedView.clickTaskListCheckbox (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:788:32)
    at MarkdownPreviewEnhancedView.webviewReceiveMessage (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:220:74)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.19.0/resources/electron.asar/renderer/web-view/web-view.js:175:22)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.19.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:79:15)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:36.9.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
auto-update-plus 0.2.0 
autoupdate-packages 1.3.1 
markdown-preview-enhanced 0.14.6 
sync-settings 0.8.2 
toggle-markdown-task 0.6.0 
```

**Comment by shd101wyy** [comment]
@miskovics might be fixed now.

**Comment by miskovics** [comment]
Tested, works.
