### ISSUE TITLE
Cannot find module '@shd101wyy/mume'

### ISSUE THREAD

**Issue by myerandme** [shd101wyy/markdown-preview-enhanced#573]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.14.7

### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At Cannot find module '@shd101wyy/mume'

Error: Cannot find module '@shd101wyy/mume'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/markdown-preview-enhanced-master/out/src/extension.js:14:14)
    at /packages/markdown-preview-enhanced-master/out/src/extension.js:515:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.19.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:1014:34
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:676:42)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:607:23
```

### Commands

```
```

### Non-Core Packages

```
simplified-chinese-menu 5.3.4 
markdown-preview-enhanced 0.14.7 
```

--- 
我使用的是 win 10 的系统，我安装了一个中文菜单的插件是没有问题，然后安装这个插件是出现了这个问题，我以前用 win 7 安装是没有问题的。

**Comment by shd101wyy** [comment]
通过官方渠道安装试试。例如 `apm install markdown-preview-enhanced`

**Comment by myerandme** [comment]
谢谢，这样安装就可以用了。
