### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isPreviewInPresentationMode' of null

### ISSUE THREAD

**Issue by changshunxu520** [shd101wyy/markdown-preview-enhanced#584]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.14.8

### Stack Trace

Uncaught TypeError: Cannot read property 'isPreviewInPresentationMode' of null

```
At C:\Users\xuchangshun\.atom\packages\markdown-preview-enhanced\out\src\preview-content-provider.js:225

TypeError: Cannot read property 'isPreviewInPresentationMode' of null
    at MarkdownPreviewEnhancedView.webviewStopLoading (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:225:25)
    at WebViewImpl.dispatchEvent (D:/atom/Atom x64/resources/electron.asar/renderer/web-view/web-view.js:175:22)
    at dispatchEvent (D:/atom/Atom x64/resources/electron.asar/renderer/web-view/guest-view-internal.js:55:11)
    at EventEmitter.<anonymous> (D:/atom/Atom x64/resources/electron.asar/renderer/web-view/guest-view-internal.js:72:55)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -6:25.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -6:15.9.0 intentions:highlight (input.hidden-input)
     -6:15.7.0 markdown-preview-plus:toggle (input.hidden-input)
     -6:03.9.0 core:backspace (input.hidden-input)
  3x -5:57.5.0 core:save (input#markdown-preview-plus.openPreviewInSplitPane.input-checkbox)
     -5:54.5.0 intentions:highlight (input.hidden-input)
     -5:54.4.0 markdown-preview-plus:toggle (input.hidden-input)
     -5:29.1.0 core:paste (input.hidden-input)
     -0:52.5.0 intentions:highlight (input.hidden-input)
     -0:52.2.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-json-color 0.6.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-java 1.2.7 
autocomplete-modules 1.6.10 
autocomplete-paths 2.8.0 
busy-signal 1.4.3 
data-atom 0.25.2 
default-encoding 0.8.0 
extjs-snippets 0.2.0 
file-icons 2.1.11 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
java-importer 1.4.1 
jquery-snippets 11.0.0 
language-markdown 0.25.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-stylelint 4.0.1 
linter-ui-default 1.6.7 
markdown-img-paste 0.3.9 
markdown-preview-enhanced 0.14.8 
markdown-preview-plus 2.4.10 
markdown-table-editor 0.6.1 
markdown-themeable-pdf 1.2.0 
pdf-view 0.59.0 
qolor 0.4.2 
script 3.15.0 
scroll-sync 0.2.3 
seti-syntax 1.1.3 
seti-ui 1.9.0 
support-gbk 2.1.1 
sync-settings 0.8.2 
```

**Comment by shd101wyy** [comment]
I will have a look tomorrow

**Comment by shd101wyy** [comment]
@changshunxu520 Fixed :)

**Comment by changshunxu520** [comment]
I will test now,Thank you

**Comment by changshunxu520** [comment]
![image](https://user-images.githubusercontent.com/16171624/29500627-117a18b0-8655-11e7-8cf0-7e30b337a720.png)
我更新到最新版本以后,仅仅是展示这个东西，没有显示出来界面。。。这是为啥。

**Comment by shd101wyy** [comment]
@changshunxu520 `View -> Developer -> Toggle Developer Tools` 看下 console 有没有报错吧？  
我的没有问题。  你谁怎么安装的呢？

**Comment by changshunxu520** [comment]
我在dev下面看到这些错误，我先卸载之后再用atom  intall 一次看看吧
Uncaught (in promise) TypeError: Cannot read property 'getPath' of undefined
    at file:///C:/Users/xuchangshun/.atom/packages/default-encoding/lib/atom-default-encoding.coffee:16:26
    at Function.module.exports.Emitter.simpleDispatch (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Workspace.<anonymous> (D:\atom\Atom x64\resources\app\src\workspace.js:1183:26)
    at Generator.next (<anonymous>)
    at step (D:\atom\Atom x64\resources\app\src\workspace.js:11:279)
C:\Users\xuchangshun\.atom\packages\default-encoding\lib\atom-default-encoding.coffee:20 Uncaught (in promise) TypeError: Cannot read property 'getPath' of undefined
    at file:///C:/Users/xuchangshun/.atom/packages/default-encoding/lib/atom-default-encoding.coffee:16:26
    at Function.module.exports.Emitter.simpleDispatch (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Workspace.<anonymous> (D:\atom\Atom x64\resources\app\src\workspace.js:1183:26)
    at Generator.next (<anonymous>)
    at step (D:\atom\Atom x64\resources\app\src\workspace.js:11:279)
C:\Users\xuchangshun\.atom\packages\markdown-preview-enhanced\out\src\preview-content-provider.js:187 Uncaught (in promise) TypeError: Cannot read property 'generateHTMLTemplateForPreview' of null
    at MarkdownPreviewEnhancedView.<anonymous> (C:\Users\xuchangshun\.atom\packages\markdown-preview-enhanced\out\src\preview-content-provider.js:187:43)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\xuchangshun\.atom\packages\markdown-preview-enhanced\out\src\preview-content-provider.js:4:58)
C:\Users\xuchangshun\.atom\packages\default-encoding\lib\atom-default-encoding.coffee:20 Uncaught (in promise) TypeError: Cannot read property 'getPath' of undefined
    at file:///C:/Users/xuchangshun/.atom/packages/default-encoding/lib/atom-default-encoding.coffee:16:26
    at Function.module.exports.Emitter.simpleDispatch (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Workspace.<anonymous> (D:\atom\Atom x64\resources\app\src\workspace.js:1183:26)
    at Generator.next (<anonymous>)
    at step (D:\atom\Atom x64\resources\app\src\workspace.js:11:279)
C:\Users\xuchangshun\.atom\packages\default-encoding\lib\atom-default-encoding.coffee:20 Uncaught (in promise) TypeError: Cannot read property 'getPath' of undefined
    at file:///C:/Users/xuchangshun/.atom/packages/default-encoding/lib/atom-default-encoding.coffee:16:26
    at Function.module.exports.Emitter.simpleDispatch (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Workspace.<anonymous> (D:\atom\Atom x64\resources\app\src\workspace.js:1183:26)
    at Generator.next (<anonymous>)
    at step (D:\atom\Atom x64\resources\app\src\workspace.js:11:279)
C:\Users\xuchangshun\.atom\packages\default-encoding\lib\atom-default-encoding.coffee:20 Uncaught (in promise) TypeError: Cannot read property 'getPath' of undefined
    at file:///C:/Users/xuchangshun/.atom/packages/default-encoding/lib/atom-default-encoding.coffee:16:26
    at Function.module.exports.Emitter.simpleDispatch (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Workspace.<anonymous> (D:\atom\Atom x64\resources\app\src\workspace.js:1183:26)
    at Generator.next (<anonymous>)
    at step (D:\atom\Atom x64\resources\app\src\workspace.js:11:279)
C:\Users\xuchangshun\.atom\packages\default-encoding\lib\atom-default-encoding.coffee:20 Uncaught (in promise) TypeError: Cannot read property 'getPath' of undefined
    at file:///C:/Users/xuchangshun/.atom/packages/default-encoding/lib/atom-default-encoding.coffee:16:26
    at Function.module.exports.Emitter.simpleDispatch (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Workspace.<anonymous> (D:\atom\Atom x64\resources\app\src\workspace.js:1183:26)
    at Generator.next (<anonymous>)
    at step (D:\atom\Atom x64\resources\app\src\workspace.js:11:279)
C:\Users\xuchangshun\.atom\packages\default-encoding\lib\atom-default-encoding.coffee:20 Uncaught (in promise) TypeError: Cannot read property 'getPath' of undefined
    at file:///C:/Users/xuchangshun/.atom/packages/default-encoding/lib/atom-default-encoding.coffee:16:26
    at Function.module.exports.Emitter.simpleDispatch (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Workspace.<anonymous> (D:\atom\Atom x64\resources\app\src\workspace.js:1183:26)
    at Generator.next (<anonymous>)
    at step (D:\atom\Atom x64\resources\app\src\workspace.js:11:279)
C:\Users\xuchangshun\.atom\packages\default-encoding\lib\atom-default-encoding.coffee:41 utf8
C:\Users\xuchangshun\.atom\packages\default-encoding\lib\atom-default-encoding.coffee:20 Uncaught (in promise) TypeError: Cannot read property 'getPath' of undefined
    at file:///C:/Users/xuchangshun/.atom/packages/default-encoding/lib/atom-default-encoding.coffee:16:26
    at Function.module.exports.Emitter.simpleDispatch (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (D:\atom\Atom x64\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Workspace.<anonymous> (D:\atom\Atom x64\resources\app\src\workspace.js:1183:26)
    at Generator.next (<anonymous>)
    at step (D:\atom\Atom x64\resources\app\src\workspace.js:11:279)

**Comment by changshunxu520** [comment]
好了,问题解决了,可以正常显示,就是显示的样式啥的没有用的markdown-preview-plus绚丽。markdown-preview-plus这个的缺点就是不能自动的滚动。这个插件要是能根据皮肤的颜色更换自己显示的样式就完美了

**Comment by shd101wyy** [comment]
嗯。原来是支持自动换皮肤的。为了和 vscode 版统一所以这个 feature 删掉了
