### ISSUE TITLE
install failed on macos

### ISSUE THREAD

**Issue by srxqds** [shd101wyy/markdown-preview-enhanced#620]
Installing “markdown-preview-enhanced@0.14.10” failed.Hide output…

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v1.6.9/iojs-v1.6.9.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 54.231.49.242:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/dsqiu/Desktop/software/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/dsqiu/Desktop/software/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.6.9" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/dsqiu/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by shd101wyy** [comment]
In recommend you to install this package from the atom editor instead of
doing so manually.

**Comment by srxqds** [comment]
I just install it in Settings/Install Package, it's ok on windows, bug fail on macos

**Comment by shd101wyy** [comment]
I think it might be internet issue? What exactly is the issue? Can you post
a screenshot?
