### ISSUE TITLE
Failed to activate the markdown-preview-enhanced package

### ISSUE THREAD

**Issue by taoeffect** [shd101wyy/markdown-preview-enhanced#66]
1. after package update, get prompt for Little Snitch to outgoing connection to is.gd, a URL obfuscator/shortener
2. block it

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.7.2
### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At ImageHelperView is not a function

TypeError: ImageHelperView is not a function
    at Object.module.exports.MarkdownPreviewEnhanced.activate (/Users/gslepak/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:20:29)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:389:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -0:54.5.0 settings-view:open (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "table-editor",
      "markdown-preview-plus",
      "tool-bar",
      "tool-bar-markdown-writer",
      "activate-power-mode",
      "imdone-atom",
      "language-pfm",
      "metrics"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "markdown-preview-enhanced": {
    "openPreviewPaneAutomatically": false
  }
}
```
### Installed Packages

``` coffee
# User
Not listed for privacy reasons

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
Hi @taoeffect

Can you restart the atom and then check if the same issue still happens?  I remembered I met the same problem.

**Comment by taoeffect** [comment]
Oh, yeah I restarted, and actually didn't need to restart for it to continue working. Sorry I should have been clear about that. I just wanted to let you know about exception. Up to you whether or not you want to close this issue.

**Comment by shd101wyy** [comment]
Oh I see. Thanks. I will go checked why it happens.

**Comment by taoeffect** [comment]
Awesome thanks! BTW I *love love love* your plugin! I love how it changes the scroll speed when images are inserted to keep the text matched (great attention to detail!), and I love the built-in LaTeX support + export to PDF/HTML.

You've really done a fantastic job! 😄 👍

**Comment by shd101wyy** [comment]
Thank you very much 😆

**Comment by shd101wyy** [comment]
closing this issue out :)
