### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroyItem' of undefined

### ISSUE THREAD

**Issue by Timhernandez** [shd101wyy/markdown-preview-enhanced#680]
[Enter steps to reproduce:]

1. open md file
2. shift+ctrl+m for markdown preview
3. error 
(Can also be reproduced with selecting from toolbar)
Restarting Atom does not solve error.

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.15.0

### Stack Trace

Uncaught TypeError: Cannot read property 'destroyItem' of undefined

```
At C:\Users\Tim\.atom\packages\markdown-preview-enhanced\out\src\extension.js:86

TypeError: Cannot read property 'destroyItem' of undefined
    at HTMLElement.togglePreview (/packages/markdown-preview-enhanced/out/src/extension.js:86:13)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -1:41.3.0 core:move-left (input.hidden-input)
     -1:39.7.0 core:backspace (input.hidden-input)
  8x -1:36.3.0 markdown-preview-enhanced:toggle (atom-text-editor.editor)
  2x -1:23.1.0 core:backspace (div#linter-panel.)
  3x -1:18.9.0 markdown-preview-enhanced:toggle (atom-text-editor.editor)
     -1:15.3.0 core:move-left (input.hidden-input)
     -1:15 core:backspace (input.hidden-input)
     -1:14.5.0 core:move-right (input.hidden-input)
 23x -1:09.2.0 markdown-preview-enhanced:toggle (atom-text-editor.editor)
     -0:23.1.0 core:backspace (input.hidden-input)
     -0:14.4.0 intentions:highlight (input.hidden-input)
     -0:14.1.0 core:save (input.hidden-input)
     -0:13 intentions:highlight (input.hidden-input)
     -0:12.6.0 markdown-preview-enhanced:toggle (input.hidden-input)
     -0:08.9.0 intentions:highlight (input.hidden-input)
     -0:08.6.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
language-markdown 0.25.1 
linter 2.2.0 
linter-markdown 5.2.0 
linter-ui-default 1.6.10 
markdown-preview-enhanced 0.15.0 
markdown-toc 0.4.2 
pdf-view 0.59.0 
```

**Comment by shd101wyy** [comment]
Try reinstalling this package?

**Comment by jroemhild** [comment]
I am running into this as well. Reinstalling didn't help. : /
