### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=407

### ISSUE THREAD

**Issue by Mikaciu** [shd101wyy/markdown-preview-enhanced#742]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0-beta2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.15.1

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=407

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=407
    at ClientRequest.onConnect (/packages/markdown-preview-enhanced/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:290:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:394:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
```

### Non-Core Packages

```
dracula-syntax 2.0.5 
language-batchfile 0.7.1 
language-mermaid 0.6.0 
language-powershell 4.0.0 
language-reg 0.0.0 
markdown-preview-enhanced 0.15.1 
minimap 4.29.7 
mr-markdown-pdf 1.6.0 
read-only-indicator 0.7.0 
scroll-sync 0.2.4 
selection-highlight 0.1.6 
sort-lines 0.18.0 
split-diff 1.5.2 
xml-formatter 0.11.0 
```

**Comment by shd101wyy** [comment]
Hmm I have no clue why that happened...
Try restarting atom then reinstall this package. Or just install this package from the terminal. `apm install markdown-preview-enhanced`
