### ISSUE TITLE
Uncaught TypeError: this.editor.getElement is not a function

### ISSUE THREAD

**Issue by YuLiumt** [shd101wyy/markdown-preview-enhanced#813]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.15.3

### Stack Trace

Uncaught TypeError: this.editor.getElement is not a function

```
At C:\Users\HUST\.atom\packages\markdown-preview-enhanced\out\src\preview-content-provider.js:436

TypeError: this.editor.getElement is not a function
    at MarkdownPreviewEnhancedView.scrollToBufferPosition (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:436:56)
    at MarkdownPreviewEnhancedView.revealLine (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:768:14)
    at MarkdownPreviewEnhancedView.webviewReceiveMessage (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:257:74)
    at WebViewImpl.dispatchEvent (C:/ProgramData/HUST/atom/app-1.24.0/resources/electron.asar/renderer/web-view/web-view.js:175:22)
    at EventEmitter.<anonymous> (C:/ProgramData/HUST/atom/app-1.24.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:79:15)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:47.1.0 core:backspace (input.hidden-input)
     -0:55.4.0 markdown-writer:open-cheat-sheet (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.32.0 
atom-clock 0.1.16 
atom-latex 0.8.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-bibtex 1.2.1 
autocomplete-date 0.4.0 
autocomplete-latex-cite 0.3.1 
autocomplete-latex-references 0.3.1 
autocomplete-math 0.1.1 
autocomplete-modules 1.11.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
color-picker 2.2.5 
convert-to-utf8 0.2.4 
docblockr 0.13.7 
file-icons 2.1.17 
gist-it 0.9.2 
git-control 0.9.0 
git-log 0.4.1 
git-plus 7.10.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-latex 1.1.1 
language-markdown 0.25.1 
latex 0.49.0 
latex-autocomplete 1.1.1 
latex-completions 0.3.3 
latex-tree 0.2.1 
latexer 0.3.0 
linter 2.2.0 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.7.1 
markdown-img-paste 0.3.9 
markdown-pdf 2.1.0 
markdown-preview-enhanced 0.15.3 
markdown-preview-plus 2.5.5 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.0 
markdown-table-formatter 2.9.2 
markdown-themeable-pdf 1.2.0 
markdown-writer 2.7.3 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
open-recent 5.0.0 
pdf-view 0.65.0 
pretty-json 2.0.0 
preview-inline 1.5.1 
python-debugger 0.2.0 
python-tools 0.6.9 
regex-railroad-diagram 0.19.4 
svg-preview 0.12.1 
sync-settings 0.8.5 
trailing-semicolon 1.1.0 
wakatime 7.0.4 
```

**Comment by shd101wyy** [comment]
大兄弟重启 atom 有用吗？

**Comment by YuLiumt** [comment]
我下载的插件太多了，也不太清楚之前遇到的是什么问题，我现在atom的markdown-preview-enhanced可以正常使用。谢谢
