### ISSUE TITLE
Uncaught AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to t...

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#83]
[Enter steps to reproduce below:]

1. open one md file
2. right click the preview window and choose export to disk/Phantonjs ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.7.9

### Stack Trace

Uncaught AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'

```
At assert.js:89

AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'
    at new PDF (/Users/wangxu/Documents/github/markdown-preview-enhanced/node_modules/html-pdf/lib/pdf.js:38:3)
    at Object.createPdf [as create] (/Users/wangxu/Documents/github/markdown-preview-enhanced/node_modules/html-pdf/lib/index.js:10:14)
    at MarkdownPreviewEnhancedView.module.exports.MarkdownPreviewEnhancedView.phantomJSExport (/Users/wangxu/Documents/github/markdown-preview-enhanced/lib/markdown-preview-enhanced-view.coffee:929:8)
    at HTMLDivElement.<anonymous> (/Users/wangxu/Documents/github/markdown-preview-enhanced/lib/exporter-view.coffee:122:26)
    at HTMLDivElement.jQuery.event.dispatch (/Users/wangxu/Documents/github/markdown-preview-enhanced/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Users/wangxu/Documents/github/markdown-preview-enhanced/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:22.9.0 awiki:openWikiIndex (atom-text-editor.editor.is-focused)
     -0:18.2.0 markdown-preview-enhanced:export-to-disk (div.markdown-preview-enhanced.native-key-bindings)
     -0:05.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "nvatom",
      "save-autorun"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "markdown-preview-enhanced": {
    "exportPDFPageFormat": "A4",
    "imageFolderPath": "assets",
    "useGitHubStyle": true,
    "useGitHubSyntaxTheme": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
awiki, v0.3.1
console-panel, v0.2.0
markdown-mindmap, v0.2.4
markdown-preview-enhanced, v0.7.9
merge-conflicts, v1.4.4
minimap, v4.24.6
on-save, v0.2.9
platformio-ide-terminal, v2.0.10
script-runner, v1.8.4

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
That means you failed to install PhantomJS. 
What operating system are you using?

**Comment by shd101wyy** [comment]
If you are blocked by the Great Firewall, then you can check this [post 中文](http://blog.csdn.net/dream_an/article/details/51800523) and

**Comment by xu4wang** [comment]
我用的 mac OS. 感觉phantomjs已经安装好了 , 命令行下可以运行。
```
bogon:markdown-preview-enhanced wangxu$ phantomjs
phantomjs> 
```

我看下那个博客。 您是王小雷？

**Comment by shd101wyy** [comment]
不，我不是。  

如果您使用的是 Mac OS。那么在 terminal 中依次运行以下的 command:

```shell
brew update 
brew install phantomjs 
cd ~/.atom/packages/markdown-preview-enhanced/
rm -rf node_modules
npm install
```

如果您没有安装 nodejs
```
brew install node
```

**Comment by xu4wang** [comment]
多谢。 OK了。 我之前是全局安装的。 刚才又本地安装了一下就可以找到了。

```
bogon:markdown-preview-enhanced wangxu$ sudo npm install phantomjs-prebuilt 
Password:
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> phantomjs-prebuilt@2.1.7 install /Users/wangxu/Documents/github/markdown-preview-enhanced/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Linking to global install at /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs
Writing location.js file
markdown-preview-enhanced@0.7.9 /Users/wangxu/Documents/github/markdown-preview-enhanced
└─┬ phantomjs-prebuilt@2.1.7 
  └─┬ request@2.67.0
    └── qs@5.2.1 


```

**Comment by xu4wang** [comment]
problem solved. thanks @shd101wyy

**Comment by supermin963** [comment]
笑死我了，为什么两个中国人用英文在交流哈哈哈哈哈哈哈
