### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getElement' of undefined

### ISSUE THREAD

**Issue by Camypaper** [shd101wyy/markdown-preview-enhanced#88]
[Enter steps to reproduce below:]

1. toggle(ON) zen mode
2. preview
3. toggle(OFF) zen mode

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package, v0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getElement' of undefined

```
At /C:/Users/goat/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:268

TypeError: Cannot read property 'getElement' of undefined
    at Object.module.exports.MarkdownPreviewEnhanced.toggleZenMode (file:///C:/Users/goat/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:241:27)
    at atom-workspace.subscriptions.add.atom.commands.add.markdown-preview-enhanced:toggle-zen-mode (file:///C:/Users/goat/.atom/packages/markdown-preview-enhanced/lib/markdown-preview-enhanced.coffee:41:56)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\goat\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -1:29.5.0 markdown-preview-enhanced:toggle (atom-text-editor.editor.is-focused)
     -1:26.6.0 settings-view:open (div.markdown-preview-enhanced.native-key-bindings)
     -1:24.4.0 command-palette:toggle (div.panels-item)
     -1:18.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:18.9.0 markdown-preview-enhanced:toggle-zen-mode (div.panels-item)
     -0:27.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:23.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.7.0 markdown-preview-enhanced:toggle-zen-mode (atom-text-editor.editor)
  2x -0:17.5.0 core:close (div.markdown-preview-enhanced.native-key-bindings)
     -0:13 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:11 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11 markdown-preview-enhanced:toggle-zen-mode (atom-text-editor.editor)
     -0:08.8.0 markdown-preview-enhanced:toggle (atom-text-editor.editor.is-focused)
     -0:05.8.0 command-palette:toggle (div.markdown-preview-enhanced.native-key-bindings)
     -0:03.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.5.0 markdown-preview-enhanced:toggle-zen-mode (div.markdown-preview-enhanced.native-key-bindings)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "packagesWithKeymapsDisabled": []
  },
  "markdown-preview-enhanced": {
    "enableWikiLinkSyntax": false,
    "openPreviewPaneAutomatically": false
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
autocomplete-go, v1.1.0
builder-go, v1.0.0
go-config, v1.2.1
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
json-schema, v0.1.15
linter, v1.11.14
linter-gcc, v0.6.15
markdown-preview-enhanced, v0.8.0
minimap, v4.24.7
navigator-godef, v1.0.3
omnisharp-atom, vundefined
pdf-view, v0.50.0
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by shd101wyy** [comment]
zen-mode is still under development (not in the doc), please don't use that command right now. 

Thanks

**Comment by Camypaper** [comment]
Thank you for reply, When I restart Atom, it was resolved, (I mean that this bug was because of update )
