### ISSUE TITLE
Uncaught TypeError: this.editor.getFileName is not a function

### ISSUE THREAD

**Issue by eportzxp** [shd101wyy/markdown-preview-enhanced#892]
[Enter steps to reproduce:]

1. When I first time use a new machine, I import the old version .md file, it appeared.
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Windows 10
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.15.6

### Stack Trace

Uncaught TypeError: this.editor.getFileName is not a function

```
At C:\Users\ThinkPad\.atom\packages\markdown-preview-enhanced\out\src\preview-content-provider.js:94

TypeError: this.editor.getFileName is not a function
    at MarkdownPreviewEnhancedView.getTitle (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:94:50)
    at Workspace.updateWindowTitle (~/AppData/Local/atom/app-1.27.1/resources/app/src/workspace.js:577:61)
    at Workspace.didChangeActivePaneItem (~/AppData/Local/atom/app-1.27.1/resources/app/src/workspace.js:458:16)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.27.1/resources/app/src/workspace.js:442:18)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.27.1/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.27.1/resources/app/src/pane-container.js:285:26)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.27.1/resources/app/src/pane-container.js:263:18)
    at Pane.activate (~/AppData/Local/atom/app-1.27.1/resources/app/src/pane.js:1018:46)
    at Pane.focus (~/AppData/Local/atom/app-1.27.1/resources/app/src/pane.js:401:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
```

### Non-Core Packages

```
markdown-preview-enhanced 0.15.6 
node_modules undefined 
seti-ui 1.10.0 
```

**Comment by kachkaev** [comment]
@eportzxp are you still experince this problem? How often does it occur?

**Comment by douglasuzcategui** [comment]
hi, 

i've the same error. @kachkaev  

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.17.0


### Stack Trace

Uncaught TypeError: this.editor.getFileName is not a function

```
At D:\Usuarios\xxxxxxx\.atom\packages\markdown-preview-enhanced\out\src\preview-content-provider.js:94

TypeError: this.editor.getFileName is not a function
    at MarkdownPreviewEnhancedView.getTitle (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:94:50)
    at Workspace.updateWindowTitle (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:427360)
    at Workspace.didChangeActivePaneItem (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:424707)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:424364)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:44396)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:446737)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:446214)
    at Pane.activate (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:463632)
    at Pane.focus (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:455075)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/web-view/web-view.js:142:22)
    at WebViewImpl.onFocusChange (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/web-view/web-view.js:183:12)
    at dispatchEvent (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/web-view/guest-view-internal.js:60:13)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/web-view/guest-view-internal.js:74:7)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
  2x -6:22.2.0 editor:newline-below (input.hidden-input)
  2x -6:19.7.0 core:undo (input.hidden-input)
     -6:17.8.0 core:redo (input.hidden-input)
     -6:13.8.0 editor:newline (input.hidden-input)
  4x -6:12.6.0 core:delete (input.hidden-input)
     -6:10.4.0 core:backspace (input.hidden-input)
     -5:57.7.0 plantuml-preview:toggle (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
graphviz-preview-plus 1.5.10 
language-dot 1.7.0 
language-plantuml 0.2.0 
markdown-preview-enhanced 0.17.0 
plantuml-preview 0.12.9 
```

**Comment by rtgilbert** [comment]
Hi,

I just experienced the error.  As it's been a while since the last report I thought it might be helpful to provide additional information for cross–reference.  I'll disable some of the non–essential packages for the project and see if it'll reproduce [Reproduced, see below.].

[Enter steps to reproduce:]

1. Open Atom, then a new draft in Markdown Writer
2. Toggle Markdown Preview Enhanced
3. Toggle Markdown Writer's cheatsheet (opens in a new tab)
4. Dragged cheatsheet tab to different location -> error

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.17.8


### Stack Trace

Uncaught TypeError: this.editor.getFileName is not a function

```
At /Users/Main/.atom/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:95

TypeError: this.editor.getFileName is not a function
    at MarkdownPreviewEnhancedView.getTitle (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:95:50)
    at TabView.updateTitle (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:14:961015)
    at new TabView (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:14:955462)
    at TabBarView.addTabForItem (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1155413)
    at /Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1153701
    at Function.simpleDispatch (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at Pane.addItem (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:458944)
    at Pane.moveItemToPane (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:460544)
    at TabBarView.moveItemBetweenPanes (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1166061)
    at TabBarView.onDrop (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1163604)
```

### Commands

```
     -3:36.4.0 markdown-writer:new-draft (input.hidden-input)
  5x -3:11.6.0 core:move-left (input.hidden-input)
     -3:10.4.0 core:backspace (input.hidden-input)
  5x -3:09.2.0 core:move-right (input.hidden-input)
     -3:01.3.0 core:confirm (input.hidden-input)
     -2:34.2.0 markdown-preview-enhanced:toggle (input.hidden-input)
     -1:47 markdown-writer:open-cheat-sheet (input.hidden-input)
```

### Non-Core Packages
*** Indicates enabled
```
academic 0.34.1 
academic-markdown 0.3.8 
atom-beautify 0.33.4 ***
atom-ide-ui 0.13.0 ***
atom-notes 1.23.0 
cheatsheet 2.0.0 
color-picker 2.3.0 
document-outline 2.1.2 
file-icons 2.1.40 
hex-view 0.2.1 ***
highlight-colors 0.9.0 
highlight-selected 0.17.0 ***
ide-css 0.3.4 
ide-json 0.2.1 
ide-r 0.1.8 
keybinding-cheatsheet 0.1.1 ***
language-markdown 0.37.0 ***
markdown-preview-enhanced 0.17.8 ***
markdown-writer 2.11.10 ***
notes-from-pdf 0.4.2 ***
pandoc-convert 1.1.1 
tool-bar 1.3.0 
tool-bar-markdown-writer 0.5.1 ***
wordcount 3.2.0 ***
zotero-citations 5.2.0 
zotero-picker 2.0.2 
```
Hex View was the only enabled extraneous package above.
[Enter steps to reproduce:]

1. Opened Atom and disabled Hex View.
2. Opened a new draft in Markdown Writer
2. Toggle Markdown Preview Enhanced
3. Toggle Markdown Writer's cheatsheet (opens in a new tab, far left)
4. Dragged cheatsheet tab to different location (far right) -> error upon drag initiation

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.17.8


### Stack Trace

Uncaught TypeError: this.editor.getFileName is not a function

```
At /Users/Main/.atom/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:95

TypeError: this.editor.getFileName is not a function
    at MarkdownPreviewEnhancedView.getTitle (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:95:50)
    at TabView.updateTitle (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:14:961015)
    at new TabView (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:14:955462)
    at TabBarView.addTabForItem (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1155413)
    at /Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1153701
    at Function.simpleDispatch (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at Pane.addItem (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:458944)
    at Pane.moveItemToPane (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:460544)
    at TabBarView.moveItemBetweenPanes (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1166061)
    at TabBarView.onDrop (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1163604)
```

### Commands

```
     -8:27.1.0 settings-view:uninstall-packages (input.hidden-input)
     -1:27.9.0 markdown-writer:new-draft (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:54.9.0 core:confirm (input.hidden-input)
     -0:33.8.0 markdown-preview-enhanced:toggle (input.hidden-input)
     -0:25 markdown-writer:open-cheat-sheet (input.hidden-input)
```

### Non-Core Packages
*** Indicates enabled
```
academic 0.34.1 
academic-markdown 0.3.8 
atom-beautify 0.33.4 ***
atom-ide-ui 0.13.0 ***
atom-notes 1.23.0 
cheatsheet 2.0.0 
color-picker 2.3.0 
document-outline 2.1.2 
file-icons 2.1.40 
hex-view 0.2.1
highlight-colors 0.9.0 
highlight-selected 0.17.0 ***
ide-css 0.3.4 
ide-json 0.2.1 
ide-r 0.1.8 
keybinding-cheatsheet 0.1.1 ***
language-markdown 0.37.0 ***
markdown-preview-enhanced 0.17.8 ***
markdown-writer 2.11.10 ***
notes-from-pdf 0.4.2 ***
pandoc-convert 1.1.1 
tool-bar 1.3.0 
tool-bar-markdown-writer 0.5.1 ***
wordcount 3.2.0 ***
zotero-citations 5.2.0 
zotero-picker 2.0.2 
```
Third attempt varied order of actions.  

1. Opened a new draft in Markdown Writer (MW)
2. Toggle Markdown Writer's cheatsheet (opens in a new tab, far left)
3. Toggle Markdown Preview Enhanced (MPE)
4. Opened a second draft in MW
5. Dragged tabs around variously at first keeping MPE on the far right, eventually dragging MPE in increments to the left beyond MW's cheatsheet.  Then able to drag each tab across the others. Entering text in either draft then dragging was null.
6. Noted that dragging MPE disconnects it from the associated MW tab.  Closed and opened MPE to test this a few times always moving MPE first.
7. After opening MPE (far right tab), dragged MW cheatsheet across MPE tab to far right -> error upon crossing MPE's tab.

!!! When MPE is not connected to a MW tab no error generates regardless of movement sequence or !!! if another draft tab moves across MPE.  In this configuration the error  throws only when MPE is !!! connected in the far right tab position and the MW cheatsheet tab drags across MPE.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.17.8


### Stack Trace

Uncaught TypeError: this.editor.getFileName is not a function

```
At /Users/Main/.atom/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:95

TypeError: this.editor.getFileName is not a function
    at MarkdownPreviewEnhancedView.getTitle (/packages/markdown-preview-enhanced/out/src/preview-content-provider.js:95:50)
    at TabView.updateTitle (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:14:961015)
    at new TabView (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:14:955462)
    at TabBarView.addTabForItem (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1155413)
    at /Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1153701
    at Function.simpleDispatch (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at Pane.addItem (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:458944)
    at Pane.moveItemToPane (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:460544)
    at TabBarView.moveItemBetweenPanes (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1166061)
    at TabBarView.onDrop (/Applications/Coding  Developer Tools/Atom.app/Contents/Resources/app/static/<embedded>:11:1163604)
```

### Commands

```
     -5:12.8.0 markdown-preview-enhanced:toggle (ul.list-inline.tab-bar.inset-panel)
     -4:36.4.0 markdown-writer:create-project-configs (ul.list-inline.tab-bar.inset-panel)
     -4:24.6.0 markdown-writer:open-cheat-sheet (ul.list-inline.tab-bar.inset-panel)
     -3:17.9.0 markdown-preview-enhanced:sync-preview (ul.list-inline.tab-bar.inset-panel)
  3x -2:58.3.0 markdown-preview-enhanced:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:57.4.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:57.2.0 editor:newline (input.hidden-input)
     -1:55.9.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:55.9.0 editor:newline (input.hidden-input)
     -1:44.1.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:44.1.0 editor:newline (input.hidden-input)
     -1:32.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:32.8.0 editor:newline (input.hidden-input)
     -0:32.3.0 core:copy (input.hidden-input)
     -0:26 core:paste (input.hidden-input)
     -0:13.4.0 markdown-writer:open-cheat-sheet (input.hidden-input)
```

### Non-Core Packages
*** Indicates enabled
```
academic 0.34.1 
academic-markdown 0.3.8 
atom-beautify 0.33.4 ***
atom-ide-ui 0.13.0 ***
atom-notes 1.23.0 
cheatsheet 2.0.0 
color-picker 2.3.0 
document-outline 2.1.2 
file-icons 2.1.40 
hex-view 0.2.1
highlight-colors 0.9.0 
highlight-selected 0.17.0 ***
ide-css 0.3.4 
ide-json 0.2.1 
ide-r 0.1.8 
keybinding-cheatsheet 0.1.1 ***
language-markdown 0.37.0 ***
markdown-preview-enhanced 0.17.8 ***
markdown-writer 2.11.10 ***
notes-from-pdf 0.4.2 ***
pandoc-convert 1.1.1 
tool-bar 1.3.0 
tool-bar-markdown-writer 0.5.1 ***
wordcount 3.2.0 ***
zotero-citations 5.2.0 
zotero-picker 2.0.2 

Hope this helps
