### ISSUE TITLE
Failed to activate the markdown-preview-enhanced package

### ISSUE THREAD

**Issue by shenqicheng** [shd101wyy/markdown-preview-enhanced#937]
just update atom from 1.28 to 1.29
and markdown-preview-enhanced failed

please help, thank you

Atom Version: 1.29.0
System: Windows7 x64
Thrown From: markdown-preview-enhanced package, [v0.15.6](https://github.com/shd101wyy/markdown-preview-enhanced/releases/tag/v0.15.6)

Cannot find module '@shd101wyy/mume'
Hide Stack Trace
```
Error: Cannot find module '@shd101wyy/mume'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\src\module-cache.js:354:58)
    at Module.require (file:///C:/Users/Administrator/AppData/Local/atom/app-1.29.0/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\markdown-preview-enhanced\out\src\extension.js:11:14)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\markdown-preview-enhanced\out\src\extension.js:566:3)
    at Module.get_Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\src\compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Administrator/AppData/Local/atom/app-1.29.0/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\static\<embedded>:96:26)
    at Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\src\package.js:782:33)
    at Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\src\package.js:220:40)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\src\package.js:901:81)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\node_modules\event-kit\lib\emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\node_modules\event-kit\lib\emitter.js:156:34)
    at PackageManager.triggerDeferredActivationHooks (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\src\package-manager.js:717:40)
    at Promise.all.then (C:\Users\Administrator\AppData\Local\atom\app-1.29.0\resources\app\src\package-manager.js:650:18)
    at <anonymous>
```

**Comment by kachkaev** [comment]
@shenqicheng can you try uninstalling and installing the atom package again?

**Comment by shenqicheng** [comment]
already uninstall it

and dowload from github  , unzip the package into 
C:\Users\Administrator\.atom\packages

issuse still occur

**Comment by kachkaev** [comment]
Unzipping `@shd101wyy/mume` should not be necessary as it should be installed automatically with `markdown-preview-enhanced` atom package. It will be placed in `C:\Users\Administrator\.atom\packages\markdown-preview-enhanced\node_modules\@shd101wyy\mume`.

Does this folder exist? What version of Windows are you using? I vaguely remember that there were issue with `@` in package names on one Windows machine I used.

**Comment by shenqicheng** [comment]
node_modules\@shd101wyy\mume.  NOT exist.

seems the markdown-preview-enhaced package can NOT installed correctly in my Win7 x64

**Comment by kachkaev** [comment]
Can you delete `markdown-preview-enhanced` package via Atom UI, close Atom, delete `C:\Users\Administrator\.atom\packages\markdown-preview-enhanced`, open Atom and install the package again? What is the contents of `C:\Users\Administrator\.atom\packages\markdown-preview-enhanced\node_modules` after this?

**Comment by shenqicheng** [comment]
thank you very much .
I 've uninstall the pack and remove the dir , reinstall successfully in a new NETWORK with out GFW.

this time , node_modules exist and full of files.

**markdown-preview-enhanced** works amazing . many thanks !

**Comment by Githomie** [comment]
Can't install properly. Tried suggestions here. Keeps getting errors.

There are files in the Users directory for it, but it doesn't seem to register correctly with Atom. It shows up as a toggle at the top, which doesn't seem to do anything. Doesn't show up under installed packages.

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.15.8


### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At Cannot find module './clone.js'

Error: Cannot find module './clone.js'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.32.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:154368)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:145675)
    at /packages/markdown-preview-enhanced/node_modules/graceful-fs/graceful-fs.js:4:13)
    at /packages/markdown-preview-enhanced/node_modules/graceful-fs/graceful-fs.js:281:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:145675)
    at /app.asar/node_modules/github/node_modules/fs-extra/lib/fs/index.js:4:12)
    at /app.asar/node_modules/github/node_modules/fs-extra/lib/fs/index.js:109:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:145675)
    at /app.asar/node_modules/github/node_modules/fs-extra/lib/index.js:8:12)
    at /app.asar/node_modules/github/node_modules/fs-extra/lib/index.js:24:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:145675)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/code-chunk.js:12:20)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/code-chunk.js:158:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:145675)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/process-graphs.js:13:22)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/process-graphs.js:278:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:145675)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/markdown-convert.js:18:26)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/markdown-convert.js:233:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:145675)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/markdown-engine.js:19:28)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/markdown-engine.js:2119:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:145675)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:22:25)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:102:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:145675)
    at /packages/markdown-preview-enhanced/out/src/extension.js:11:14)
    at /packages/markdown-preview-enhanced/out/src/extension.js:566:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:1:622321)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:3044031)
    at Package.activateNow (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:3032165)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:1186953)
    at Emitter.emit (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:1188394)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:380240)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:380202)
    at ~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:913914
    at r (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:908520)
    at o (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:1037411)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:1037617)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -8:35.7.0 core:paste (div.placeholder-text)
```

### Non-Core Packages

```
MaPerWiki 0.1.27 
markdown-preview-enhanced 0.15.8 
markdown-writer 2.10.3 
tool-bar 1.1.10 
tool-bar-markdown-writer 0.5.0 
```

**Comment by marozols** [comment]
I just installed the package and immediately got this error. I tried the suggestions above (e.g., disabling the built-in markdown preview, reinstalling the package, or installing it manually via GitHub) but nothing seems to help. Any suggestions?

**Atom**: 1.36.0 x64
**Electron**: 4.1.1
**OS**: "Manjaro Linux"
**Thrown From**: [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package 0.15.10


### Stack Trace

Failed to activate the markdown-preview-enhanced package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (<anonymous>)
    at field (/packages/markdown-preview-enhanced/node_modules/vega-util/build/vega-util.js:110:7)
    at /packages/markdown-preview-enhanced/node_modules/vega-util/build/vega-util.js:118:12
    at /packages/markdown-preview-enhanced/node_modules/vega-util/build/vega-util.js:2:66
    at /packages/markdown-preview-enhanced/node_modules/vega-util/build/vega-util.js:5:2)
    at /packages/markdown-preview-enhanced/node_modules/vega-util/build/vega-util.js:814:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/markdown-preview-enhanced/node_modules/vega-loader/build/vega-loader.node.js:5:16)
    at /packages/markdown-preview-enhanced/node_modules/vega-loader/build/vega-loader.node.js:416:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/vega.js:12:23)
    at /packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/vega.js:62:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
```

### Commands

```
     -2:01.4.0 settings-view:open (input.hidden-input)
  2x -1:53.5.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.5 
language-latex 1.2.0 
latex 0.50.2 
markdown-preview-enhanced 0.15.10 
```

**Comment by xandercrews** [comment]
@marozols are you on archlinux?  i had same issue and this guy figured it out - https://github.com/shd101wyy/markdown-preview-enhanced/issues/1111#issuecomment-485996121

atom in arch community abs is different than the official distribution, this AUR package referenced is closer to official distribution, and a new install of this package works in the latter but breaks the former.

**Comment by marozols** [comment]
Thanks, installing [atom-editor-bin](https://aur.archlinux.org/packages/atom-editor-bin/) from AUR did the job!

**Comment by miskovics** [comment]
I have this on Windows 10 64bit and reinstalling does not fix the problem.

`C:\Users\*\.atom\packages\markdown-preview-enhanced\` disappears after uninstalling the package and closing Atom, and `C:\Users\*\.atom\packages\markdown-preview-enhanced\node_modules` is populated after installing the package again, but still the same error.

Any idea what to do?

**Comment by miskovics** [comment]
> 
> 
> I have this on Windows 10 64bit and reinstalling does not fix the problem.
> 
> `C:\Users\*\.atom\packages\markdown-preview-enhanced\` disappears after uninstalling the package and closing Atom, and `C:\Users\*\.atom\packages\markdown-preview-enhanced\node_modules` is populated after installing the package again, but still the same error.
> 
> Any idea what to do?

I uninstalled Atom, deleted all related files and registry entries, installed Atom, restored all packages and settings with `sync-settings` and now everything seems to be OK.
