### ISSUE TITLE
Occasionally Unable to Toggle Preview Dialog

### ISSUE THREAD

**Issue by ihmcjacky** [shd101wyy/markdown-preview-enhanced#963]
Occasionally I cannot toggle the markdown preview enhanced dialog, the following console log has been captured from atom

```
Uncaught (in promise) Error: watch /home/myName/.mume ENOSPC
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1386:19)
    at Object.fs.watch (fs.js:1412:11)
    at Object.<anonymous> (/home/myName/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:43:12)
    at Generator.next (<anonymous>)
    at fulfilled (/home/myName/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/out/src/mume.js:4:58)
    at <anonymous>
```

Please advice, thank you

**Comment by 2E0PGS** [comment]
I had this same issue just now. I found it's because of Linux watches. 

I saw an error in the console of Atom referencing watches and found Ubuntu 18.04 has a lower `cat /proc/sys/fs/inotify/max_user_watches` than previous versions for some reason. 

I set it to a higher number and this package worked fine after reloading it: `# echo 524288 > /proc/sys/fs/inotify/max_user_watches`

**Comment by 2E0PGS** [comment]
#732

**Comment by extraymond** [comment]
Can confirm the workaround @2E0PGS  provided solve my problem with the following setup:

1. OS: ubuntu 18.04
2. Atom: 1.38.2(snap package)
3. Extension: 0.16.3
